// IPC channel names — single source of truth for both main and preload.

export const IPC = {
  ptyCreate: 'pty:create',
  ptyWrite: 'pty:write',
  ptyResize: 'pty:resize',
  ptyFlow: 'pty:flow',
  ptyKill: 'pty:kill',
  ptyDestroy: 'pty:destroy',
  ptyGenerateName: 'pty:generate-name',
  ptyCapture: 'pty:capture',
  ptySendText: 'pty:send-text',
  claudeReadTranscript: 'claude:read-transcript',
  appToggleMarkdown: 'app:toggle-markdown',
  appCloseNode: 'app:close-node',
  appCloseWindow: 'app:close-window',
  appNotify: 'app:notify',
  appFocusNode: 'app:focus-node',
  appSetBadge: 'app:set-badge',
  agentStatus: 'agent:status',
  agentSubagentActivity: 'agent:subagent-activity',
  bridgeConfigPath: 'bridge:config-path',
  bridgeSetTopology: 'bridge:set-topology',
  bridgeMessage: 'bridge:message',
  appUpdateAvailable: 'app:update-available',
  appUpdateDownloaded: 'app:update-downloaded',
  appUpdateProgress: 'app:update-progress',
  appUpdateError: 'app:update-error',
  appUpdateNotAvailable: 'app:update-not-available',
  appCheckForUpdates: 'app:check-for-updates',
  appGetVersion: 'app:get-version',
  appUpdatePolicy: 'app:update-policy',
  licenseActivate: 'license:activate',
  licenseDeactivate: 'license:deactivate',
  licenseStatus: 'license:status',
  licenseChanged: 'license:changed',
  licenseUpgrade: 'license:upgrade',
  appRestartToUpdate: 'app:restart-to-update',
  announcementsFetch: 'announcements:fetch',
  usageFetch: 'usage:fetch',
  usageRefresh: 'usage:refresh',
  usageUpdate: 'usage:update',
  contextUpdate: 'context:update',
  // Events broadcast from main to the renderer (sessionId is appended to the channel name).
  ptyData: (sessionId: string) => `pty:data:${sessionId}`,
  ptyExit: (sessionId: string) => `pty:exit:${sessionId}`,
  workspaceLoad: 'workspace:load',
  workspaceSave: 'workspace:save',
  dialogSelectFolder: 'dialog:select-folder',
  dialogSelectFile: 'dialog:select-file',
  shellReveal: 'shell:reveal',
  shellOpenPath: 'shell:open-path',
  fsList: 'fs:list',
  fsRead: 'fs:read',
  fsReadBinary: 'fs:read-binary',
  fsWrite: 'fs:write',
  settingsLoad: 'settings:load',
  settingsSave: 'settings:save',
  gitStatus: 'git:status',
  gitInit: 'git:init',
  gitClone: 'git:clone',
  gitCommit: 'git:commit',
  gitPush: 'git:push',
  gitPull: 'git:pull',
  gitSync: 'git:sync',
  gitPublish: 'git:publish',
  gitStage: 'git:stage',
  gitUnstage: 'git:unstage',
  gitStageAll: 'git:stage-all',
  gitUnstageAll: 'git:unstage-all',
  gitDiff: 'git:diff',
  gitDiscard: 'git:discard',
  gitSwitchBranch: 'git:switch-branch',
  gitCreateBranch: 'git:create-branch',
  gitShowFile: 'git:show-file',
  gitHistory: 'git:history',
  gitCommitFiles: 'git:commit-files',
  gitRemoteCommitUrl: 'git:remote-commit-url',
  shellOpenExternal: 'shell:open-external',
  commitGenerate: 'commit:generate',
  remoteHostStart: 'remote:host:start',
  remoteHostStop: 'remote:host:stop',
  // Host canvas mirror: renderer pushes its serialized active-project canvas to main;
  // main pushes a client's mutation back to the host renderer to apply.
  remoteHostCanvasState: 'remote:host:canvas-state',
  remoteHostApplyMutation: 'remote:host:apply-mutation',
  // Remote-access CLIENT (drives a host's PTYs over the relay).
  remoteClientConnect: 'remote:client:connect',
  remoteClientDisconnect: 'remote:client:disconnect',
  remoteClientCreate: 'remote:client:create',
  remoteClientWrite: 'remote:client:write',
  remoteClientResize: 'remote:client:resize',
  remoteClientKill: 'remote:client:kill',
  // Per-session events broadcast main->renderer (connectionId + streamId appended).
  remoteClientData: (connectionId: string, streamId: number) =>
    `remote:client:data:${connectionId}:${streamId}`,
  remoteClientExit: (connectionId: string, streamId: number) =>
    `remote:client:exit:${connectionId}:${streamId}`,
  // Fired when a connection's relay socket drops (host/relay gone).
  remoteClientClosed: (connectionId: string) => `remote:client:closed:${connectionId}`,
  handoffBuild: 'handoff:build'
} as const
