import os from 'os'
import fs from 'fs'
import path from 'path'
import { execFileSync } from 'child_process'
import { app, ipcMain, webContents } from 'electron'
import * as pty from 'node-pty'
import { IPC } from '../shared/ipc'
import { DEFAULT_SETTINGS, type PtyCreateOptions, type Settings } from '../shared/types'
import { claudeHookDir } from './claude-hooks'

// A dedicated tmux socket isolates our sessions from the user's own tmux server.
const TMUX_SOCKET = 'node-terminal'

// Minimal tmux config so the user's ~/.tmux.conf never interferes. The tmux server
// (under our socket) keeps sessions alive while no client is attached, which is what
// gives us continuity across node remounts and full app restarts.
function tmuxConf(scrollback: number): string {
  return `# auto-generated by node-terminal — do not edit
set -g status off
set -g mouse on
set -g history-limit ${Math.max(1000, scrollback)}
set -g default-terminal "xterm-256color"
set -sg escape-time 10
set -g destroy-unattached off
setw -g aggressive-resize on
`
}

/** Resolve an absolute tmux path (GUI apps don't inherit the shell PATH). */
function findTmux(): string | null {
  for (const c of ['/opt/homebrew/bin/tmux', '/usr/local/bin/tmux', '/usr/bin/tmux', '/bin/tmux']) {
    try {
      if (fs.existsSync(c)) return c
    } catch {
      // ignore
    }
  }
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v tmux'], {
      encoding: 'utf-8'
    }).trim()
    if (out) return out
  } catch {
    // ignore
  }
  return null
}

/** tmux session names may not contain '.', ':' or whitespace. */
function sessionName(persistKey: string): string {
  return `nt-${persistKey.replace(/[^a-zA-Z0-9_-]/g, '_')}`
}

interface Session {
  proc: pty.IPty
  webContentsId: number
}

/**
 * Manages all live PTY processes and bridges them to the renderer over IPC.
 *
 * On macOS/Linux with tmux available, each terminal node attaches to a persistent
 * tmux session named after its node id (`tmux new-session -A`). Closing a node's
 * window only detaches the client — the tmux session (and everything running in it)
 * survives, so reopening the node or restarting the app reattaches and continues
 * where it left off. Without tmux, it falls back to a plain shell (no persistence).
 */
export class PtyManager {
  private sessions = new Map<string, Session>()
  private counter = 0
  private tmuxPath: string | null = null
  private confPath = ''
  private getSettings: () => Settings = () => DEFAULT_SETTINGS

  /** Must run after app is ready (needs userData path). */
  init(getSettings: () => Settings): void {
    this.getSettings = getSettings
    this.tmuxPath = findTmux()
    if (!this.tmuxPath) return
    this.confPath = path.join(app.getPath('userData'), 'tmux.conf')
    try {
      fs.writeFileSync(this.confPath, tmuxConf(getSettings().tmuxScrollback))
    } catch {
      // If we can't write the config, disable tmux and fall back to a plain shell.
      this.tmuxPath = null
    }
  }

  registerIpc(): void {
    ipcMain.handle(IPC.ptyCreate, (event, options: PtyCreateOptions) =>
      this.create(event.sender.id, options)
    )
    ipcMain.on(IPC.ptyWrite, (_event, sessionId: string, data: string) =>
      this.write(sessionId, data)
    )
    ipcMain.on(IPC.ptyResize, (_event, sessionId: string, cols: number, rows: number) =>
      this.resize(sessionId, cols, rows)
    )
    ipcMain.on(IPC.ptyKill, (_event, sessionId: string) => this.kill(sessionId))
    ipcMain.on(IPC.ptyDestroy, (_event, persistKey: string) => this.destroySession(persistKey))
    ipcMain.handle(IPC.ptySendText, (_event, persistKey: string, text: string) =>
      this.sendText(persistKey, text)
    )
  }

  private create(webContentsId: number, options: PtyCreateOptions): string {
    const sessionId = `pty-${++this.counter}`
    const cwd = options.cwd || os.homedir()

    // Strip TMUX so tmux doesn't refuse to nest if the app itself was launched
    // from inside a tmux session.
    const env = { ...process.env, TERM: 'xterm-256color' } as Record<string, string>
    delete env.TMUX
    delete env.TMUX_PANE

    // Claude Code hooks: each session carries its node id + the signal dir. Our managed
    // hook (installed globally in ~/.claude/settings.json, but a no-op without these vars)
    // then reports state back to us for any `claude` run in this session.
    const hookDir = claudeHookDir()
    env.NODETERM_HOOK_DIR = hookDir
    if (options.persistKey) env.NODETERM_NODE_ID = options.persistKey

    const settings = this.getSettings()
    let file: string
    let args: string[]

    if (this.tmuxPath && settings.tmuxEnabled && options.persistKey) {
      // attach-or-create the persistent session for this node; -D detaches any stale client.
      // `-e` sets the session environment explicitly (the tmux server is shared, so relying
      // on the client's inherited env would leak the first session's values into later ones).
      file = this.tmuxPath
      args = [
        '-L',
        TMUX_SOCKET,
        '-f',
        this.confPath,
        'new-session',
        '-A',
        '-D',
        '-e',
        `NODETERM_NODE_ID=${options.persistKey}`,
        '-e',
        `NODETERM_HOOK_DIR=${hookDir}`,
        '-c',
        cwd,
        '-s',
        sessionName(options.persistKey)
      ]
      // Honor a custom default shell at session creation (ignored on reattach).
      const shell = options.shell || settings.defaultShell
      if (shell) args.push(shell)
    } else {
      file =
        options.shell ||
        settings.defaultShell ||
        process.env.SHELL ||
        (os.platform() === 'win32' ? 'powershell.exe' : 'bash')
      args = []
    }

    const proc = pty.spawn(file, args, {
      name: 'xterm-256color',
      cols: options.cols,
      rows: options.rows,
      cwd,
      env
    })

    proc.onData((data) => {
      this.send(webContentsId, IPC.ptyData(sessionId), data)
    })

    proc.onExit(({ exitCode }) => {
      this.send(webContentsId, IPC.ptyExit(sessionId), exitCode)
      this.sessions.delete(sessionId)
    })

    this.sessions.set(sessionId, { proc, webContentsId })
    return sessionId
  }

  private write(sessionId: string, data: string): void {
    this.sessions.get(sessionId)?.proc.write(data)
  }

  private resize(sessionId: string, cols: number, rows: number): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    // cols/rows must be at least 1, otherwise node-pty throws.
    session.proc.resize(Math.max(1, cols), Math.max(1, rows))
  }

  /**
   * Detach the client. With tmux this only kills our client process; the tmux
   * session keeps running so it can be reattached later.
   */
  kill(sessionId: string): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    session.proc.kill()
    this.sessions.delete(sessionId)
  }

  /**
   * Capture a session's output. `full` grabs the entire scrollback (`-S -`, for the
   * markdown view); otherwise the recent ~200 lines (AI naming, palette search).
   */
  captureSession(persistKey: string, full = false): string {
    if (!this.tmuxPath) return ''
    try {
      return execFileSync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-t', sessionName(persistKey), '-S', full ? '-' : '-200'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
    } catch {
      return ''
    }
  }

  /**
   * Send literal text followed by Enter into a node's tmux session (e.g. a slash command).
   * Works whether or not a client is attached. Returns false if tmux is unavailable or the
   * session doesn't exist yet.
   */
  sendText(persistKey: string, text: string): boolean {
    if (!this.tmuxPath) return false
    const target = sessionName(persistKey)
    try {
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, '-l', text], {
        stdio: 'ignore'
      })
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, 'Enter'], {
        stdio: 'ignore'
      })
      return true
    } catch {
      return false
    }
  }

  /** Permanently end a node's persistent tmux session (called when the user closes it). */
  destroySession(persistKey: string): void {
    if (!this.tmuxPath) return
    try {
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'kill-session', '-t', sessionName(persistKey)], {
        stdio: 'ignore'
      })
    } catch {
      // session may not exist; ignore
    }
  }

  /**
   * On quit, detach all clients (do NOT kill tmux sessions — that's the whole point
   * of persistence). The tmux server keeps the sessions alive for next launch.
   */
  killAll(): void {
    for (const { proc } of this.sessions.values()) proc.kill()
    this.sessions.clear()
  }

  private send(webContentsId: number, channel: string, payload: unknown): void {
    const wc = webContents.fromId(webContentsId)
    if (wc && !wc.isDestroyed()) wc.send(channel, payload)
  }
}
