import os from 'os'
import fs from 'fs'
import path from 'path'
import { execFile, execFileSync } from 'child_process'
import { promisify } from 'util'
import { app, ipcMain, webContents } from 'electron'
import * as pty from 'node-pty'
import { IPC } from '../shared/ipc'
import {
  DEFAULT_SETTINGS,
  type PtyCreateOptions,
  type PtyCreateResult,
  type Settings
} from '../shared/types'
import { hookServer } from '../core/agents/hook-server'
import {
  remoteHookEnvArgs,
  remoteTmuxHasSessionArgs,
  remoteTmuxKillArgs,
  remoteTmuxPtyArgs,
  remoteCapturePaneArgs
} from './remote-ssh/control-master'
import { TMUX_SOCKET, sessionName } from '../core/tmux-naming'
import { releasePty, type ReleasablePty } from '../core/pty-release'
import { machOArch, archMismatch } from '../core/macho-arch'
import { writeScrollback, readScrollback, deleteScrollback } from '../core/scrollback-store'
import { claudeConfigDirFor } from './claude-accounts'
import { AUTH_ENV_STRIP, accountTmuxEnvArgs, remoteAccountConfigDirAbs } from '../core/claude-accounts-core'

// How often we snapshot a live tmux session's scrollback to disk, so a machine reboot (which
// kills the tmux server) can still replay recent output on cold restart. A final snapshot also
// runs on detach; the interval covers an ungraceful power loss between detaches.
const SCROLLBACK_SNAPSHOT_MS = 15_000

// Async exec for tmux side-calls (capture / send-keys / kill-session) so they never block
// the main event loop — a synchronous capture-pane of a large scrollback would stall every
// other session's PTY streaming and all IPC for its duration.
const runAsync = promisify(execFile)

// Minimal tmux config so the user's ~/.tmux.conf never interferes. The tmux server
// (under our socket) keeps sessions alive while no client is attached, which is what
// gives us continuity across node remounts and full app restarts.
function tmuxConf(scrollback: number): string {
  return `# auto-generated by node-terminal — do not edit
set -g status off
set -g mouse on
set -g history-limit ${Math.max(1000, scrollback)}
set -g default-terminal "xterm-256color"
set -sg escape-time 10
set -g destroy-unattached off
setw -g aggressive-resize on
set -g set-clipboard on
# With mouse on, a drag in a normal-screen shell makes a tmux copy-mode selection (not an
# xterm one), so the renderer's Cmd+C can't see it. Pipe the selection straight to the macOS
# clipboard when the drag ends — so mouse-select copies like a native terminal (iTerm-style).
bind -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
# Double-click word / triple-click line also copy to the clipboard.
bind -T copy-mode    DoubleClick1Pane send-keys -X select-word \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi DoubleClick1Pane send-keys -X select-word \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode    TripleClick1Pane send-keys -X select-line \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi TripleClick1Pane send-keys -X select-line \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
`
}

/** Resolve an absolute tmux path (GUI apps don't inherit the shell PATH). */
function findTmux(): string | null {
  for (const c of ['/opt/homebrew/bin/tmux', '/usr/local/bin/tmux', '/usr/bin/tmux', '/bin/tmux']) {
    try {
      if (fs.existsSync(c)) return c
    } catch {
      // ignore
    }
  }
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v tmux'], {
      encoding: 'utf-8'
    }).trim()
    if (out) return out
  } catch {
    // ignore
  }
  return null
}

/** Resolve an absolute ssh path (GUI apps don't inherit the shell PATH). */
let cachedSsh: string | null | undefined
/**
 * macOS-only diagnostic for the recurring release-clobber incident: `electron-builder --x64`
 * rebuilds node-pty IN PLACE in node_modules, leaving an x86_64 spawn-helper that an arm64 app
 * cannot posix_spawn — every terminal then fails with an opaque "posix_spawnp failed.". Returns
 * the precise message (with the `npm run rebuild` remedy) when the helper's arch mismatches this
 * process, else null. Fail-open: any read/parse problem returns null (diagnostics only).
 */
function spawnHelperArchMismatch(): string | null {
  if (os.platform() !== 'darwin') return null
  try {
    const helper = path.join(
      path.dirname(require.resolve('node-pty/package.json')),
      'build',
      'Release',
      'spawn-helper'
    )
    const fd = fs.openSync(helper, 'r')
    const buf = Buffer.alloc(8)
    fs.readSync(fd, buf, 0, 8, 0)
    fs.closeSync(fd)
    const arch = machOArch(buf)
    if (archMismatch(arch, process.arch)) {
      return (
        `node-pty's spawn-helper is ${arch} but this app is ${process.arch} — a cross-arch ` +
        `release build clobbered node_modules. Fix: run \`npm run rebuild\`, then restart the app.`
      )
    }
  } catch {
    /* diagnostics only — never mask the real spawn error */
  }
  return null
}

function findSsh(): string | null {
  if (cachedSsh !== undefined) return cachedSsh
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v ssh'], {
      encoding: 'utf-8'
    }).trim()
    cachedSsh = out || null
  } catch {
    cachedSsh = null
  }
  // Common fallback locations if the login shell lookup failed.
  if (!cachedSsh) {
    for (const p of ['/usr/bin/ssh', '/usr/local/bin/ssh', '/opt/homebrew/bin/ssh']) {
      try {
        execFileSync(p, ['-V'], { stdio: 'ignore' })
        cachedSsh = p
        break
      } catch {
        // keep trying
      }
    }
  }
  return cachedSsh ?? null
}

/**
 * Resolve the user's REAL login-shell PATH once, and cache it.
 *
 * A GUI app launched from Finder/Dock inherits only a minimal PATH
 * (`/usr/bin:/bin:/usr/sbin:/sbin`) — it never sees `/usr/local/bin`, Homebrew
 * (`/opt/homebrew/bin`), `~/.local/bin`, nvm, bun, etc. So terminals we spawn would report
 * `command not found: claude` even though the tool is installed. We run the user's login +
 * interactive shell (so BOTH profile files and `.zshrc`/`.bashrc` PATH additions are seen) and
 * read back `$PATH`, printed between sentinels to survive any dotfile noise. Bounded by a timeout;
 * on any failure (hang, dotfile error, non-POSIX shell, Windows) we fall back to the inherited PATH.
 */
let cachedShellPath: string | null | undefined
let shellPathPromise: Promise<string | null> | null = null
function resolveShellPath(): Promise<string | null> {
  if (cachedShellPath !== undefined) return Promise.resolve(cachedShellPath)
  if (shellPathPromise) return shellPathPromise
  if (os.platform() === 'win32') {
    cachedShellPath = null
    return Promise.resolve(null)
  }
  const shell = process.env.SHELL || '/bin/bash'
  const START = '__NT_PATH_START__'
  const END = '__NT_PATH_END__'
  // `-ilc` = login + interactive (matches VS Code's shell-env resolution): sources the profile
  // files AND the interactive rc (`.zshrc`/`.bashrc`) where users commonly add nvm/bun/etc.
  // Dotfiles routinely take hundreds of ms (nvm/conda init) and can hang, so this MUST be
  // async — a synchronous probe here froze every window and all IPC for up to the 5s timeout.
  // Prewarmed from init(); create() awaits it, so terminals still always get the real PATH.
  // stderr is captured separately by execFile, so prompt/compinit noise can't pollute stdout.
  shellPathPromise = runAsync(shell, ['-ilc', `command printf '${START}%s${END}' "$PATH"`], {
    encoding: 'utf-8',
    timeout: 5000
  })
    .then(({ stdout }) => {
      const m = stdout.match(new RegExp(`${START}([\\s\\S]*?)${END}`))
      return m?.[1]?.trim() || null
    })
    .catch(() => null) // login shell hung / errored / isn't POSIX — inherited-PATH fallback
    .then((resolved) => {
      cachedShellPath = resolved
      return resolved
    })
  return shellPathPromise
}

/**
 * A UTF-8 locale for spawned terminals, or null to leave the inherited locale untouched.
 *
 * A GUI app launched from Finder/Dock inherits NO locale env (no LANG/LC_*), so `locale` falls
 * back to "C" (non-UTF-8). TUIs that probe for UTF-8 support (Claude Code and other Ink/ncurses
 * apps) then render ASCII box-drawing — rounded borders come out as `_`/`|`. Same root cause as
 * the missing-PATH problem: the GUI process never sourced the shell environment. If the inherited
 * env already declares a UTF-8 locale (e.g. the app was launched from a terminal), keep it;
 * otherwise force `en_US.UTF-8`, which is always installed on macOS and guarantees UTF-8 handling.
 */
function resolveLocaleLang(): string | null {
  const cur = process.env.LC_ALL || process.env.LC_CTYPE || process.env.LANG || ''
  return /utf-?8/i.test(cur) ? null : 'en_US.UTF-8'
}

/**
 * Resolve an executable against the user's real login-shell PATH (reusing the cached probe),
 * returning its absolute path or null. GUI apps inherit only a minimal PATH, so a bare
 * `execFile('claude', …)` would fail even when the tool is installed — this walks the resolved
 * PATH entries and returns the first `bin` that exists and is accessible.
 */
export async function findInLoginPath(bin: string): Promise<string | null> {
  const shellPath = (await resolveShellPath()) ?? process.env.PATH ?? ''
  for (const dir of shellPath.split(path.delimiter)) {
    if (!dir) continue
    const candidate = path.join(dir, bin)
    try {
      await fs.promises.access(candidate, fs.constants.X_OK)
      return candidate
    } catch {
      // not here — keep looking
    }
  }
  return null
}

interface Session {
  proc: pty.IPty
  /** Renderer webContents to stream output to over IPC, or null for a detached (host) session. */
  webContentsId: number | null
  /** Detached sinks: when set, output/exit go to these callbacks instead of IPC (relay host). */
  onData?: (data: string) => void
  onExit?: (exitCode: number) => void
  /** Pending output chunks, coalesced into one IPC message per flush. */
  buf: string[]
  bufBytes: number
  flushTimer: ReturnType<typeof setTimeout> | null
  /** Node id this session persists under (when tmux-backed) — used for scrollback snapshots. */
  persistKey?: string
  /** When set, the session runs on a remote host via ssh; kill/capture target the REMOTE tmux. */
  sshRemote?: NonNullable<PtyCreateOptions['sshRemote']>
  /** Output arrived since the last scrollback snapshot — idle sessions skip the capture. */
  outputSinceSnapshot: boolean
  /** True when this node had an `accountId` but its config dir was gone at spawn, so we fell back
   *  to the system account. `create()` surfaces it to the renderer (warning chip). */
  accountFallback?: boolean
}

/** Sinks for a detached session whose output is served somewhere other than the renderer
 * (the relay host). The PTY is otherwise identical to a normal session. */
export interface DetachedSinks {
  onData(data: string): void
  onExit(exitCode: number): void
}

// Output coalescing: a fast producer (e.g. `yes`, a verbose build, tmux full-screen
// redraws) emits many small chunks. Buffering them for one short window collapses N
// IPC messages + N xterm writes into one, which is the single hottest path in the app.
const FLUSH_MS = 8
const MAX_BUF_BYTES = 256 * 1024

/**
 * Manages all live PTY processes and bridges them to the renderer over IPC.
 *
 * On macOS/Linux with tmux available, each terminal node attaches to a persistent
 * tmux session named after its node id (`tmux new-session -A`). Closing a node's
 * window only detaches the client — the tmux session (and everything running in it)
 * survives, so reopening the node or restarting the app reattaches and continues
 * where it left off. Without tmux, it falls back to a plain shell (no persistence).
 */
export class PtyManager {
  private sessions = new Map<string, Session>()
  private counter = 0
  private tmuxPath: string | null = null
  private confPath = ''
  private getSettings: () => Settings = () => DEFAULT_SETTINGS
  /** ONE shared snapshot interval for all persisted sessions — a per-session interval spawned
   *  one tmux/ssh capture subprocess per session per tick, forever, even for idle terminals. */
  private snapshotTimer: ReturnType<typeof setInterval> | null = null

  private ensureSnapshotTimer(): void {
    if (this.snapshotTimer) return
    this.snapshotTimer = setInterval(() => this.snapshotTick(), SCROLLBACK_SNAPSHOT_MS)
  }

  private snapshotTick(): void {
    let anyPersisted = false
    for (const session of this.sessions.values()) {
      if (!session.persistKey) continue
      anyPersisted = true
      if (!session.outputSinceSnapshot) continue // idle since the last capture — skip the spawn
      session.outputSinceSnapshot = false
      void this.snapshotScrollback(session.persistKey, session.sshRemote).then((ok) => {
        // Transient capture failure (ssh blip, tmux busy): put the dirty bit back so the next
        // tick retries — otherwise a quiet session would never be snapshotted again.
        if (!ok) session.outputSinceSnapshot = true
      })
    }
    if (!anyPersisted && this.snapshotTimer) {
      clearInterval(this.snapshotTimer)
      this.snapshotTimer = null
    }
  }

  /** Must run after app is ready (needs userData path). */
  init(getSettings: () => Settings): void {
    this.getSettings = getSettings
    // Prewarm the login-shell PATH probe now so the first terminal spawn doesn't wait on it.
    void resolveShellPath()
    this.tmuxPath = findTmux()
    if (!this.tmuxPath) return
    this.confPath = path.join(app.getPath('userData'), 'tmux.conf')
    try {
      fs.writeFileSync(this.confPath, tmuxConf(getSettings().tmuxScrollback))
    } catch {
      // If we can't write the config, disable tmux and fall back to a plain shell.
      this.tmuxPath = null
      return
    }
    // The tmux server outlives the app, so it won't re-read `-f` on relaunch. Push the
    // (possibly updated) config into a running server now so new bindings apply immediately;
    // a no-op error when no server exists yet (the next session loads it fresh via `-f`).
    try {
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'source-file', this.confPath], {
        stdio: 'ignore'
      })
    } catch {
      // no server running yet — ignore
    }
  }

  /** Absolute tmux path (or null if tmux is unavailable). Used by the context-link backend. */
  getTmuxBin(): string | null {
    return this.tmuxPath
  }

  registerIpc(): void {
    ipcMain.handle(
      IPC.ptyCreate,
      (event, options: PtyCreateOptions): Promise<PtyCreateResult> =>
        this.create(event.sender.id, options)
    )
    ipcMain.on(IPC.ptyWrite, (_event, sessionId: string, data: string) =>
      this.write(sessionId, data)
    )
    ipcMain.on(IPC.ptyResize, (_event, sessionId: string, cols: number, rows: number) =>
      this.resize(sessionId, cols, rows)
    )
    ipcMain.on(IPC.ptyFlow, (_event, sessionId: string, resume: boolean) =>
      this.setFlow(sessionId, resume)
    )
    ipcMain.on(IPC.ptyKill, (_event, sessionId: string) => this.kill(sessionId))
    ipcMain.on(IPC.ptyDestroy, (_event, persistKey: string) => this.destroySession(persistKey))
    ipcMain.handle(IPC.ptyReadScrollback, (_event, persistKey: string) =>
      readScrollback(persistKey)
    )
    ipcMain.handle(IPC.ptySendText, (_event, persistKey: string, text: string) =>
      this.sendText(persistKey, text)
    )
  }

  private async create(
    webContentsId: number,
    options: PtyCreateOptions
  ): Promise<PtyCreateResult> {
    // A tmux-backed session is "fresh" (cold start) when no live session exists to reattach to
    // — i.e. first open, or after a machine reboot killed the tmux server. Plain (non-tmux)
    // sessions are always fresh: they have no cross-restart continuity. The renderer uses this
    // to decide whether to replay the persisted scrollback and re-launch a resumable agent.
    const tmuxBacked =
      !!this.tmuxPath && this.getSettings().tmuxEnabled && !!options.persistKey
    // For an SSH-project node, "fresh" is decided by the REMOTE tmux server (over the project's
    // ControlMaster), not the local one. The remote `has-session` is a full network round-trip,
    // so it MUST be async (`runAsync`) — a synchronous probe here would freeze every window/IPC
    // for its duration. Falls through to the local tmux/plain logic otherwise (also async: a
    // bulk project load fires one create() per node, and even cheap probes add up serialized).
    const fresh = options.sshRemote
      ? !(await this.remoteSessionExists(
          options.sshRemote,
          sessionName(options.persistKey as string)
        ))
      : tmuxBacked
        ? !(await this.tmuxSessionExists(options.persistKey as string))
        : true
    // Ensure the login-shell PATH is resolved (prewarmed in init(); usually already settled)
    // so the session env below picks it up — awaiting keeps the event loop free either way.
    await resolveShellPath()
    const sessionId = this.spawnSession(options, webContentsId, undefined)
    // Surface a missing-account-dir fallback so the renderer can flag the node's account chip.
    const accountFallback = this.sessions.get(sessionId)?.accountFallback
    return accountFallback ? { sessionId, fresh, accountFallback } : { sessionId, fresh }
  }

  /** Does the node's remote tmux session exist (over the project's ControlMaster)? Async so the
   *  network round-trip never blocks the main event loop. */
  private async remoteSessionExists(
    sshRemote: NonNullable<PtyCreateOptions['sshRemote']>,
    sessionId: string
  ): Promise<boolean> {
    const ssh = findSsh()
    if (!ssh) return false
    try {
      await runAsync(ssh, remoteTmuxHasSessionArgs(sshRemote.conn, sshRemote.controlPath, sessionId))
      return true
    } catch {
      return false
    }
  }

  /** Find the live session registered under a node id (persistKey), if any. */
  private sessionByPersistKey(persistKey: string): Session | undefined {
    for (const session of this.sessions.values()) {
      if (session.persistKey === persistKey) return session
    }
    return undefined
  }

  /**
   * The live SSH-remote handle for a node id, if its session is running on a remote host.
   * Used by the remote context/subagent tails to read the node's transcript over the same
   * ControlMaster. Returns undefined for local sessions or unknown nodes.
   */
  sshRemoteForNode(
    nodeId: string
  ): { controlPath: string; conn: import('../shared/ssh').SshConnection } | undefined {
    const s = this.sessionByPersistKey(nodeId)
    if (!s?.sshRemote) return undefined
    return { controlPath: s.sshRemote.controlPath, conn: s.sshRemote.conn }
  }

  /** Whether a tmux session for this node id currently exists (server alive + session present).
   *  Async like the remote probe: a bulk project load fires one `create()` per terminal node,
   *  and a synchronous subprocess per probe would serialize on the main event loop. */
  private async tmuxSessionExists(persistKey: string): Promise<boolean> {
    if (!this.tmuxPath) return false
    try {
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'has-session', '-t', sessionName(persistKey)])
      return true
    } catch {
      return false
    }
  }

  /**
   * Spawn a PTY whose output/exit are delivered to `sinks` instead of the renderer. Used by
   * the relay host (Task 6) to serve PTYs over the E2EE transport: the host pipes `onData`
   * into `OP.Output` frames and maps client RPC/frames back to `write`/`resize`/`kill`. The
   * spawn (tmux session, hook env, shell selection) is identical to a normal renderer session.
   */
  createDetached(options: PtyCreateOptions, sinks: DetachedSinks): string {
    return this.spawnSession(options, null, sinks)
  }

  /**
   * Attach a detached (relay-served) PTY to the EXISTING tmux session for a node id, rather
   * than always creating a fresh one. Because `spawnSession` uses `tmux new-session -A`, passing
   * the node id as the `persistKey` reattaches the existing `nt-<nodeId>` session if it exists,
   * or creates it otherwise (graceful fallback). Used by the relay host so a mirrored terminal
   * resumes the host's live session instead of opening a blank shell. Pair with `captureSnapshot`
   * to paint the current screen before live output starts streaming. Because `sinks` is set here,
   * `spawnSession` attaches WITHOUT `-D` (co-attach), so the host's own local tmux client stays
   * attached and both the host and the mirroring client view the same session simultaneously.
   */
  attachDetached(
    persistKey: string,
    sinks: DetachedSinks,
    options: Omit<PtyCreateOptions, 'persistKey'> = { cols: 80, rows: 24 }
  ): string {
    return this.spawnSession({ ...options, persistKey }, null, sinks)
  }

  /**
   * Capture the CURRENT visible pane of a node's tmux session (with colors, via `-e`). Returns
   * the screen text so the relay host can send it as a snapshot the mirrored client paints before
   * live output. Empty string if tmux is unavailable or the session doesn't exist yet.
   */
  async captureSnapshot(persistKey: string): Promise<string> {
    if (!this.tmuxPath) return ''
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-e', '-t', sessionName(persistKey)],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      return stdout
    } catch {
      return ''
    }
  }

  private spawnSession(
    options: PtyCreateOptions,
    webContentsId: number | null,
    sinks: DetachedSinks | undefined
  ): string {
    const sessionId = `pty-${++this.counter}`
    // For a remote (ssh-project) node the local PTY just holds the ssh client, so its local cwd
    // must be a real LOCAL directory (options.cwd is a REMOTE path that wouldn't exist locally and
    // would make pty.spawn throw). The remote working dir is passed to tmux via sshRemote.remoteCwd.
    let cwd = options.sshRemote ? os.homedir() : options.cwd || os.homedir()
    // `|| os.homedir()` only catches an EMPTY cwd. A cwd that is set but STALE — a project folder
    // the user deleted/unmounted — still reaches pty.spawn and makes posix_spawn fail. Verify the
    // directory actually exists and fall back to home if not, so a dead folder never kills the node.
    if (!options.sshRemote) {
      try {
        if (!fs.statSync(cwd).isDirectory()) cwd = os.homedir()
      } catch {
        cwd = os.homedir()
      }
    }

    // Strip TMUX so tmux doesn't refuse to nest if the app itself was launched
    // from inside a tmux session.
    const env = { ...process.env, TERM: 'xterm-256color' } as Record<string, string>
    delete env.TMUX
    delete env.TMUX_PANE

    // A GUI app launched from Finder/Dock inherits only a minimal PATH, so spawned terminals
    // couldn't find tools in /usr/local/bin, Homebrew, ~/.local/bin, nvm, bun, etc. (the classic
    // `command not found: claude`). Replace PATH with the user's real login-shell PATH so every
    // terminal — and any agent CLI it launches — resolves exactly what a normal terminal would.
    // Reads the cache filled by the async probe: create() awaits it, and the detached/host
    // paths spawn late enough that the init()-time prewarm has long since settled.
    const shellPath = cachedShellPath ?? null
    if (shellPath) env.PATH = shellPath

    // Same GUI-launch gap for the locale: with no LANG/LC_* the shell's `locale` is "C" (non-UTF-8),
    // so Claude Code and other TUIs fall back to ASCII box-drawing (rounded borders render as `_`/`|`).
    // Force a UTF-8 locale when the inherited env doesn't already declare one.
    const localeLang = resolveLocaleLang()
    if (localeLang) env.LANG = localeLang

    // Agent hooks: each session carries the hook-server coordinates + its node/agent id.
    // Our managed hook (installed globally in each agent's config, but a no-op without these
    // vars) then posts state back to us for any agent run in this session.
    // A REMOTE (ssh-project) session must NOT get the LOCAL hook env: it points at
    // 127.0.0.1:<localPort>, which is useless (and misleading) on the remote host. The remote
    // session's hook env is injected via the remote tmux `-e` below (from the reverse-tunnel
    // endpoint file), so leave the local hook env out entirely here.
    const hookEnv =
      options.persistKey && !options.sshRemote
        ? hookServer.buildPtyEnv(options.persistKey, options.agentId ?? 'claude')
        : {}
    for (const [k, v] of Object.entries(hookEnv)) env[k] = v

    // Managed Claude account: the whole session runs under the account's private config
    // dir. The claude CLI then reads/writes credentials + transcripts there. Also strip
    // env auth vars that would silently shadow the account's OAuth login (an inherited
    // ANTHROPIC_API_KEY wins over CLAUDE_CONFIG_DIR credentials). System-default nodes
    // (no accountId) are untouched. Remote (ssh) sessions get their account env via the
    // remote tmux `-e` list instead (the local ssh client process doesn't need it).
    let accountDir =
      options.accountId && !options.sshRemote ? claudeConfigDirFor(options.accountId) : null
    // Missing/deleted account dir (spec: error handling) → fall back to system default
    // instead of pointing claude at a dead dir; the node then behaves like an unbound one.
    // `accountFallback` is surfaced to the renderer (warning chip) via the create() result.
    let accountFallback = false
    if (accountDir && !fs.existsSync(accountDir)) {
      console.warn(`[accounts] config dir missing for ${options.accountId}, using system default`)
      accountDir = null
      accountFallback = true
    }
    if (accountDir) {
      env.CLAUDE_CONFIG_DIR = accountDir
      for (const k of AUTH_ENV_STRIP) delete env[k]
    }

    const settings = this.getSettings()
    let file: string
    let args: string[]

    // Resolve the session program. A bare 'ssh' is resolved to an absolute path because GUI
    // apps don't inherit the shell PATH; its args come from options.shellArgs.
    const reqShell = options.shell
    const program = reqShell === 'ssh' ? findSsh() ?? 'ssh' : reqShell
    const programArgs = options.shellArgs ?? []

    // SSH project node: run `ssh -t '<remote tmux attach-or-create>'` as the PTY program. The
    // REMOTE tmux provides persistence (over the project's ControlMaster); the local PTY just
    // holds the ssh client. Only when BOTH sshRemote and persistKey are set and ssh resolves —
    // otherwise this falls through to the unchanged local-tmux / plain-shell branches below.
    const remoteSsh = options.sshRemote && options.persistKey ? findSsh() : null
    if (options.sshRemote && options.persistKey && remoteSsh) {
      file = remoteSsh
      // When the project's reverse tunnel + remote endpoint file are set up (Task 2), inject the
      // remote hook env into the remote tmux session so the installed hook script POSTs state back
      // over the unix-socket tunnel. Fail-open: no hookEndpointPath → no hook env (Phase-1 status).
      //
      // NODETERM_NODE_ID MUST be the RAW persistKey (the React Flow node id), NOT the tmux
      // session name (`nt-<id>`). The local path's hookServer.buildPtyEnv(persistKey, …) sets
      // NODETERM_NODE_ID = persistKey, and Canvas.tsx onAgentStatus keys agentStatus.byId /
      // selection off that raw id with no `nt-` stripping. Passing the session name here would
      // emit events under `nt-<id>` that match no node → no badge/notification/session/loop.
      const hookExtraEnv = options.sshRemote.hookEndpointPath
        ? remoteHookEnvArgs(
            options.sshRemote.hookEndpointPath,
            options.persistKey,
            hookServer.getVersion()
          )
        : []
      // Managed REMOTE Claude account (Task 12): inject CLAUDE_CONFIG_DIR into the remote tmux
      // session via `-e`, pointing at the account's config dir on the remote host. The path must be
      // ABSOLUTE — tmux copies `-e` values verbatim (no `$HOME`/`~` expansion) — so we build it from
      // the connection's resolved remote $HOME. Fail-open: an unknown remoteHome (home resolution
      // failed on connect) skips the account env and the session runs under the remote `~/.claude`.
      const remoteAccountEnv =
        options.accountId && options.sshRemote.remoteHome
          ? accountTmuxEnvArgs(remoteAccountConfigDirAbs(options.sshRemote.remoteHome, options.accountId))
          : []
      args = remoteTmuxPtyArgs(
        options.sshRemote.conn,
        options.sshRemote.controlPath,
        sessionName(options.persistKey),
        options.sshRemote.remoteCwd,
        // An agent preset may pass a remote program to run inside the remote tmux; usually undefined.
        options.shell,
        options.shellArgs,
        [...hookExtraEnv, ...remoteAccountEnv],
        // Source nodeterm's remote tmux.conf via `-f` (written on connect, Task 2) so a cold-start
        // session gets mouse/clipboard/scrollback. Fail-open: undefined → remote tmux host defaults.
        options.sshRemote.tmuxConfPath
      )
    } else if (this.tmuxPath && settings.tmuxEnabled && options.persistKey) {
      // attach-or-create the persistent session for this node.
      // `-A` = attach-or-create. `-D` = detach OTHER clients on attach. We use `-D` ONLY for the
      // local renderer client (a remount should take sole ownership of its session). A host-served
      // PTY (sinks set) MUST NOT detach others: the host's own local client is attached to the same
      // `nt-<id>` session, and a connecting client should MIRROR it (tmux co-attach), not kick it
      // off — `-D` there is exactly what showed "[detached]" in every host window on connect.
      // (tmux sizes a co-attached session to the smallest client — the accepted mirroring tradeoff.)
      // `-e` sets the session environment explicitly (the tmux server is shared, so relying
      // on the client's inherited env would leak the first session's values into later ones).
      file = this.tmuxPath
      // The hook-server env (port/token/node id/agent id) is passed explicitly via `-e`
      // (one `-e KEY=VALUE` per key) since the shared tmux server can't rely on inherited env.
      const hookEnvArgs = Object.entries(hookEnv).flatMap(([k, v]) => ['-e', `${k}=${v}`])
      // Set the session PATH explicitly too: the tmux server is shared and long-lived (it outlives
      // the app), so a session created after an app update must NOT inherit a stale minimal PATH
      // baked into the server env at first launch — `-e` overrides it per new session at creation.
      const pathEnvArgs = env.PATH ? ['-e', `PATH=${env.PATH}`] : []
      // Same reasoning for LANG: force the UTF-8 locale per new session so a session created on a
      // shared/stale tmux server (started before this fix) still gets UTF-8 box-drawing.
      const langEnvArgs = env.LANG ? ['-e', `LANG=${env.LANG}`] : []
      // The account config dir must ride `-e` like the hook env: the tmux server is shared
      // and long-lived, so session env comes from creation args, not client inheritance.
      const accountEnvArgs = accountDir ? accountTmuxEnvArgs(accountDir) : []
      const attachFlags = sinks ? ['-A'] : ['-A', '-D']
      args = [
        '-L',
        TMUX_SOCKET,
        '-f',
        this.confPath,
        'new-session',
        ...attachFlags,
        ...hookEnvArgs,
        ...pathEnvArgs,
        ...langEnvArgs,
        ...accountEnvArgs,
        '-c',
        cwd,
        '-s',
        sessionName(options.persistKey)
      ]
      // Honor a custom session program at creation (ignored on reattach).
      const shell = program || settings.defaultShell
      if (shell) {
        args.push(shell)
        args.push(...programArgs)
      }
    } else {
      file =
        program ||
        settings.defaultShell ||
        process.env.SHELL ||
        (os.platform() === 'win32' ? 'powershell.exe' : 'bash')
      args = program ? programArgs : []
    }

    let proc: pty.IPty
    try {
      proc = pty.spawn(file, args, {
        name: 'xterm-256color',
        cols: options.cols,
        rows: options.rows,
        cwd,
        env
      })
    } catch (err) {
      // node-pty surfaces the underlying failure as a bare "posix_spawnp failed." with no errno.
      // The recurring field cause is a cross-arch `electron-builder --x64` run clobbering
      // node-pty's spawn-helper in node_modules (arm64 app can't exec an x86_64 helper), so
      // check the helper's Mach-O arch first and name the exact remedy when it mismatches.
      const openPtys = this.sessions.size
      const reason = err instanceof Error ? err.message : String(err)
      const archNote = spawnHelperArchMismatch()
      throw new Error(
        `Failed to spawn terminal (${reason}). Program: ${file}, cwd: ${cwd}, live PTYs: ${openPtys}. ` +
          (archNote ??
            `If this persists, restart the app (tmux sessions survive a restart) or run ` +
              `\`npm run rebuild\` in the repo — a release build may have rebuilt node-pty ` +
              `for the wrong architecture.`)
      )
    }

    // tmux-backed sessions snapshot their scrollback to disk periodically so a machine reboot
    // (which kills the tmux server) can still replay recent output on cold restart. A remote
    // (ssh-project) node is persisted too — the snapshot is captured from the REMOTE tmux.
    // Mark the session remote ONLY when the remote branch above actually ran (`remoteSsh` resolved).
    // If ssh is missing, the node fell through to a LOCAL tmux/plain spawn, so it must NOT be
    // marked remote — otherwise destroy/capture would target a remote tmux that was never spawned
    // and silently leak the local session.
    const remote = options.sshRemote && options.persistKey && remoteSsh ? options.sshRemote : undefined
    const tmuxBacked = !!(this.tmuxPath && settings.tmuxEnabled && options.persistKey)
    const persisted = !!options.persistKey && (remote ? true : tmuxBacked)
    const session: Session = {
      proc,
      webContentsId,
      onData: sinks?.onData,
      onExit: sinks?.onExit,
      buf: [],
      bufBytes: 0,
      flushTimer: null,
      persistKey: persisted ? options.persistKey : undefined,
      sshRemote: remote,
      outputSinceSnapshot: true, // capture the initial screen on the first tick
      accountFallback
    }
    if (persisted) this.ensureSnapshotTimer()
    this.sessions.set(sessionId, session)

    proc.onData((data) => this.queueData(sessionId, session, data))

    proc.onExit(({ exitCode }) => {
      this.flush(sessionId, session) // deliver any buffered output before the exit signal
      if (session.onExit) {
        session.onExit(exitCode)
      } else if (webContentsId !== null) {
        this.send(webContentsId, IPC.ptyExit(sessionId), exitCode)
      }
      this.sessions.delete(sessionId)
    })

    return sessionId
  }

  /** Buffer a chunk; flush immediately past the byte cap, otherwise on a short timer. */
  private queueData(sessionId: string, session: Session, data: string): void {
    session.outputSinceSnapshot = true
    session.buf.push(data)
    session.bufBytes += data.length
    if (session.bufBytes >= MAX_BUF_BYTES) {
      this.flush(sessionId, session)
    } else if (!session.flushTimer) {
      session.flushTimer = setTimeout(() => this.flush(sessionId, session), FLUSH_MS)
    }
  }

  /** Send all buffered output for a session as a single IPC message. */
  private flush(sessionId: string, session: Session): void {
    if (session.flushTimer) {
      clearTimeout(session.flushTimer)
      session.flushTimer = null
    }
    if (session.buf.length === 0) return
    const data = session.buf.join('')
    session.buf = []
    session.bufBytes = 0
    if (session.onData) {
      session.onData(data)
    } else if (session.webContentsId !== null) {
      this.send(session.webContentsId, IPC.ptyData(sessionId), data)
    }
  }

  /**
   * Flow control: the renderer pauses us when xterm's write backlog grows past a high
   * watermark and resumes once it drains, so a flood can't grow the renderer buffer
   * without bound. node-pty pause()/resume() stops/starts reading the pty fd; the OS
   * pipe applies backpressure to the producing process.
   */
  setFlow(sessionId: string, resume: boolean): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    try {
      if (resume) session.proc.resume()
      else session.proc.pause()
    } catch {
      // pause/resume can throw if the proc already exited; ignore.
    }
  }

  write(sessionId: string, data: string): void {
    this.sessions.get(sessionId)?.proc.write(data)
  }

  resize(sessionId: string, cols: number, rows: number): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    // cols/rows must be at least 1, otherwise node-pty throws.
    session.proc.resize(Math.max(1, cols), Math.max(1, rows))
  }

  /**
   * Detach the client. With tmux this only kills our client process; the tmux
   * session keeps running so it can be reattached later.
   */
  kill(sessionId: string): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    if (session.flushTimer) clearTimeout(session.flushTimer)
    // Final snapshot on detach (node unmount / app quit) so the very latest scrollback survives
    // a reboot. The tmux session itself keeps running, so this only races a same-instant capture.
    // Skipped when nothing arrived since the last periodic capture (pane content is unchanged).
    if (session.persistKey && session.outputSinceSnapshot)
      void this.snapshotScrollback(session.persistKey, session.sshRemote)
    // releasePty (not proc.kill()): a paused pty never reads EOF, so kill() alone leaks the
    // master fd on every detach until the process runs out of descriptors (see pty-release.ts).
    releasePty(session.proc as ReleasablePty)
    this.sessions.delete(sessionId)
  }

  /**
   * Capture a session's output. `full` grabs the entire scrollback (`-S -`, for the
   * markdown view); otherwise the recent ~200 lines (AI naming, palette search).
   */
  async captureSession(persistKey: string, full = false): Promise<string> {
    // Remote (ssh-project) node: there is no local tmux session — capture from the REMOTE tmux
    // over the project's ControlMaster (mirrors snapshotScrollback / destroySession).
    const sshRemote = this.sessionByPersistKey(persistKey)?.sshRemote
    if (sshRemote) {
      const ssh = findSsh()
      if (!ssh) return ''
      try {
        const { stdout } = await runAsync(
          ssh,
          remoteCapturePaneArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey), full),
          { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
        )
        return stdout
      } catch {
        return ''
      }
    }
    if (!this.tmuxPath) return ''
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-t', sessionName(persistKey), '-S', full ? '-' : '-200'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      return stdout
    } catch {
      return ''
    }
  }

  /**
   * Snapshot a node's recent scrollback (with colors, `-e`) to disk for cold-restart replay.
   * Best-effort: a missing session / unavailable tmux just leaves the prior snapshot in place.
   * Returns false when the capture failed, so the periodic tick can re-mark the session dirty
   * and retry (the dirty bit is cleared optimistically before the capture starts).
   */
  private async snapshotScrollback(
    persistKey: string,
    sshRemote?: NonNullable<PtyCreateOptions['sshRemote']>
  ): Promise<boolean> {
    if (sshRemote) {
      // Remote (ssh-project) node: capture from the REMOTE tmux over the project's ControlMaster.
      const ssh = findSsh()
      if (!ssh) return false
      try {
        const { stdout } = await runAsync(
          ssh,
          remoteCapturePaneArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey), false),
          { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
        )
        if (stdout) await writeScrollback(persistKey, stdout)
        return true
      } catch {
        // remote session gone / master down — keep the last good snapshot
        return false
      }
    }
    if (!this.tmuxPath) return false
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-e', '-t', sessionName(persistKey), '-S', '-1500'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      if (stdout) await writeScrollback(persistKey, stdout)
      return true
    } catch {
      // session gone / tmux unavailable — keep the last good snapshot
      return false
    }
  }

  /**
   * Send literal text followed by Enter into a node's tmux session (e.g. a slash command).
   * Works whether or not a client is attached. Returns false if tmux is unavailable or the
   * session doesn't exist yet.
   */
  async sendText(persistKey: string, text: string): Promise<boolean> {
    if (!this.tmuxPath) return false
    const target = sessionName(persistKey)
    try {
      // The literal text and the Enter must be sent in order, so await sequentially.
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, '-l', text])
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, 'Enter'])
      return true
    } catch {
      return false
    }
  }

  /** Permanently end a node's persistent tmux session (called when the user closes it). */
  async destroySession(persistKey: string): Promise<void> {
    // destroy() is called (close button) while the session is still live, so its sshRemote is
    // known. Capture it synchronously before any await.
    const sshRemote = this.sessionByPersistKey(persistKey)?.sshRemote
    // The node is gone for good — drop its cold-restore snapshot too.
    await deleteScrollback(persistKey)
    if (sshRemote) {
      // Remote (ssh-project) node: there is no local tmux session — end the REMOTE one.
      const ssh = findSsh()
      if (!ssh) return
      try {
        await runAsync(ssh, remoteTmuxKillArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey)))
      } catch {
        // remote session may not exist / master down; ignore
      }
      return
    }
    if (!this.tmuxPath) return
    try {
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'kill-session', '-t', sessionName(persistKey)])
    } catch {
      // session may not exist; ignore
    }
  }

  /**
   * On quit, detach all clients (do NOT kill tmux sessions — that's the whole point
   * of persistence). The tmux server keeps the sessions alive for next launch.
   */
  /** Returns a promise of the final scrollback snapshots: the capture + write are async, so
   *  the quit path must hold `before-quit` briefly (see index.ts) or the process exits before
   *  they land and the last ≤15s of output is missing from a post-reboot cold restore. */
  killAll(): Promise<void> {
    if (this.snapshotTimer) {
      clearInterval(this.snapshotTimer)
      this.snapshotTimer = null
    }
    const finals: Promise<unknown>[] = []
    for (const session of this.sessions.values()) {
      if (session.flushTimer) clearTimeout(session.flushTimer)
      // Final scrollback snapshot on quit so a reboot can replay it. Skipped for sessions with
      // no output since the last periodic capture (unchanged pane content).
      if (session.persistKey && session.outputSinceSnapshot)
        finals.push(this.snapshotScrollback(session.persistKey, session.sshRemote))
      releasePty(session.proc as ReleasablePty)
    }
    this.sessions.clear()
    return Promise.all(finals).then(() => undefined)
  }

  private send(webContentsId: number, channel: string, payload: unknown): void {
    const wc = webContents.fromId(webContentsId)
    if (wc && !wc.isDestroyed()) wc.send(channel, payload)
  }
}
