import os from 'os'
import fs from 'fs'
import path from 'path'
import { execFile, execFileSync } from 'child_process'
import { promisify } from 'util'
import { platform } from './platform'
import * as pty from 'node-pty'
import { IPC } from '../shared/ipc'
import {
  DEFAULT_SETTINGS,
  type PtyCreateOptions,
  type PtyCreateResult,
  type Settings
} from '../shared/types'
import { hookServer } from './agents/hook-server'
import {
  remoteHookEnvArgs,
  remoteTmuxHasSessionArgs,
  remoteTmuxKillArgs,
  remoteTmuxPtyArgs,
  remoteCapturePaneArgs
} from './remote-ssh/control-master'
import { TMUX_SOCKET, sessionName } from './tmux-naming'
import { releasePty, type ReleasablePty } from './pty-release'
import { effectiveSize, type PtySize } from './pty-size'
import { machOArch, archMismatch } from './macho-arch'
import { writeScrollback, readScrollback, deleteScrollback } from './scrollback-store'
import { claudeConfigDirFor } from './claude-config-dir'
import { AUTH_ENV_STRIP, accountTmuxEnvArgs, remoteAccountConfigDirAbs } from './claude-accounts-core'

// How often we snapshot a live tmux session's scrollback to disk, so a machine reboot (which
// kills the tmux server) can still replay recent output on cold restart. A final snapshot also
// runs on detach; the interval covers an ungraceful power loss between detaches.
const SCROLLBACK_SNAPSHOT_MS = 15_000

// Async exec for tmux side-calls (capture / send-keys / kill-session) so they never block
// the main event loop — a synchronous capture-pane of a large scrollback would stall every
// other session's PTY streaming and all IPC for its duration.
const runAsync = promisify(execFile)

// Minimal tmux config so the user's ~/.tmux.conf never interferes. The tmux server
// (under our socket) keeps sessions alive while no client is attached, which is what
// gives us continuity across node remounts and full app restarts.
function tmuxConf(scrollback: number): string {
  return `# auto-generated by node-terminal — do not edit
set -g status off
set -g mouse on
set -g history-limit ${Math.max(1000, scrollback)}
set -g default-terminal "xterm-256color"
set -sg escape-time 10
set -g destroy-unattached off
setw -g aggressive-resize on
set -g set-clipboard on
# With mouse on, a drag in a normal-screen shell makes a tmux copy-mode selection (not an
# xterm one), so the renderer's Cmd+C can't see it. Pipe the selection straight to the macOS
# clipboard when the drag ends — so mouse-select copies like a native terminal (iTerm-style).
bind -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
# Double-click word / triple-click line also copy to the clipboard.
bind -T copy-mode    DoubleClick1Pane send-keys -X select-word \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi DoubleClick1Pane send-keys -X select-word \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode    TripleClick1Pane send-keys -X select-line \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
bind -T copy-mode-vi TripleClick1Pane send-keys -X select-line \\; send-keys -X copy-pipe-and-cancel "/usr/bin/pbcopy"
`
}

/** Resolve an absolute tmux path (GUI apps don't inherit the shell PATH). */
function findTmux(): string | null {
  for (const c of ['/opt/homebrew/bin/tmux', '/usr/local/bin/tmux', '/usr/bin/tmux', '/bin/tmux']) {
    try {
      if (fs.existsSync(c)) return c
    } catch {
      // ignore
    }
  }
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v tmux'], {
      encoding: 'utf-8'
    }).trim()
    if (out) return out
  } catch {
    // ignore
  }
  return null
}

/** Resolve an absolute ssh path (GUI apps don't inherit the shell PATH). */
let cachedSsh: string | null | undefined
/**
 * macOS-only diagnostic for the recurring release-clobber incident: `electron-builder --x64`
 * rebuilds node-pty IN PLACE in node_modules, leaving an x86_64 spawn-helper that an arm64 app
 * cannot posix_spawn — every terminal then fails with an opaque "posix_spawnp failed.". Returns
 * the precise message (with the `npm run rebuild` remedy) when the helper's arch mismatches this
 * process, else null. Fail-open: any read/parse problem returns null (diagnostics only).
 */
function spawnHelperArchMismatch(): string | null {
  if (os.platform() !== 'darwin') return null
  try {
    const helper = path.join(
      path.dirname(require.resolve('node-pty/package.json')),
      'build',
      'Release',
      'spawn-helper'
    )
    const fd = fs.openSync(helper, 'r')
    const buf = Buffer.alloc(8)
    fs.readSync(fd, buf, 0, 8, 0)
    fs.closeSync(fd)
    const arch = machOArch(buf)
    if (archMismatch(arch, process.arch)) {
      return (
        `node-pty's spawn-helper is ${arch} but this app is ${process.arch} — a cross-arch ` +
        `release build clobbered node_modules. Fix: run \`npm run rebuild\`, then restart the app.`
      )
    }
  } catch {
    /* diagnostics only — never mask the real spawn error */
  }
  return null
}

function findSsh(): string | null {
  if (cachedSsh !== undefined) return cachedSsh
  try {
    const out = execFileSync(process.env.SHELL || '/bin/bash', ['-lc', 'command -v ssh'], {
      encoding: 'utf-8'
    }).trim()
    cachedSsh = out || null
  } catch {
    cachedSsh = null
  }
  // Common fallback locations if the login shell lookup failed.
  if (!cachedSsh) {
    for (const p of ['/usr/bin/ssh', '/usr/local/bin/ssh', '/opt/homebrew/bin/ssh']) {
      try {
        execFileSync(p, ['-V'], { stdio: 'ignore' })
        cachedSsh = p
        break
      } catch {
        // keep trying
      }
    }
  }
  return cachedSsh ?? null
}

/**
 * Resolve the user's REAL login-shell PATH once, and cache it.
 *
 * A GUI app launched from Finder/Dock inherits only a minimal PATH
 * (`/usr/bin:/bin:/usr/sbin:/sbin`) — it never sees `/usr/local/bin`, Homebrew
 * (`/opt/homebrew/bin`), `~/.local/bin`, nvm, bun, etc. So terminals we spawn would report
 * `command not found: claude` even though the tool is installed. We run the user's login +
 * interactive shell (so BOTH profile files and `.zshrc`/`.bashrc` PATH additions are seen) and
 * read back `$PATH`, printed between sentinels to survive any dotfile noise. Bounded by a timeout;
 * on any failure (hang, dotfile error, non-POSIX shell, Windows) we fall back to the inherited PATH.
 */
let cachedShellPath: string | null | undefined
let shellPathPromise: Promise<string | null> | null = null
function resolveShellPath(): Promise<string | null> {
  if (cachedShellPath !== undefined) return Promise.resolve(cachedShellPath)
  if (shellPathPromise) return shellPathPromise
  if (os.platform() === 'win32') {
    cachedShellPath = null
    return Promise.resolve(null)
  }
  const shell = process.env.SHELL || '/bin/bash'
  const START = '__NT_PATH_START__'
  const END = '__NT_PATH_END__'
  // `-ilc` = login + interactive (matches VS Code's shell-env resolution): sources the profile
  // files AND the interactive rc (`.zshrc`/`.bashrc`) where users commonly add nvm/bun/etc.
  // Dotfiles routinely take hundreds of ms (nvm/conda init) and can hang, so this MUST be
  // async — a synchronous probe here froze every window and all IPC for up to the 5s timeout.
  // Prewarmed from init(); create() awaits it, so terminals still always get the real PATH.
  // stderr is captured separately by execFile, so prompt/compinit noise can't pollute stdout.
  shellPathPromise = runAsync(shell, ['-ilc', `command printf '${START}%s${END}' "$PATH"`], {
    encoding: 'utf-8',
    timeout: 5000
  })
    .then(({ stdout }) => {
      const m = stdout.match(new RegExp(`${START}([\\s\\S]*?)${END}`))
      return m?.[1]?.trim() || null
    })
    .catch(() => null) // login shell hung / errored / isn't POSIX — inherited-PATH fallback
    .then((resolved) => {
      cachedShellPath = resolved
      return resolved
    })
  return shellPathPromise
}

/**
 * A UTF-8 locale for spawned terminals, or null to leave the inherited locale untouched.
 *
 * A GUI app launched from Finder/Dock inherits NO locale env (no LANG/LC_*), so `locale` falls
 * back to "C" (non-UTF-8). TUIs that probe for UTF-8 support (Claude Code and other Ink/ncurses
 * apps) then render ASCII box-drawing — rounded borders come out as `_`/`|`. Same root cause as
 * the missing-PATH problem: the GUI process never sourced the shell environment. If the inherited
 * env already declares a UTF-8 locale (e.g. the app was launched from a terminal), keep it;
 * otherwise force `en_US.UTF-8`, which is always installed on macOS and guarantees UTF-8 handling.
 */
function resolveLocaleLang(): string | null {
  const cur = process.env.LC_ALL || process.env.LC_CTYPE || process.env.LANG || ''
  return /utf-?8/i.test(cur) ? null : 'en_US.UTF-8'
}

/**
 * Resolve an executable against the user's real login-shell PATH (reusing the cached probe),
 * returning its absolute path or null. GUI apps inherit only a minimal PATH, so a bare
 * `execFile('claude', …)` would fail even when the tool is installed — this walks the resolved
 * PATH entries and returns the first `bin` that exists and is accessible.
 */
export async function findInLoginPath(bin: string): Promise<string | null> {
  const shellPath = (await resolveShellPath()) ?? process.env.PATH ?? ''
  for (const dir of shellPath.split(path.delimiter)) {
    if (!dir) continue
    const candidate = path.join(dir, bin)
    try {
      await fs.promises.access(candidate, fs.constants.X_OK)
      return candidate
    } catch {
      // not here — keep looking
    }
  }
  return null
}

/** A UI client: an Electron webContents id or a ServerPlatform uiId. */
type ClientId = number

/** One client's reported fit, run through the same floor/clamp the pty itself gets, so a size we
 *  record for a client is comparable with the effective size we compute from all of them. */
function normalizeSize(cols: number, rows: number): PtySize {
  return effectiveSize([{ cols, rows }]) as PtySize // one entry in ⇒ never null out
}

interface Session {
  proc: pty.IPty
  /** Every UI watching this session. Co-attach: ONE pty and ONE tmux client, N subscribers —
   *  a second client on the same persistKey joins this set instead of spawning a second tmux
   *  client (whose `-D` would then kick the first one off). Empty for a purely detached
   *  (relay-served) session. */
  subscribers: Set<ClientId>
  /** Each VIEWING subscriber's last reported cols/rows — the pty runs at the min of these
   *  (`effectiveSize`). A subscriber that is subscribed but NOT looking is ABSENT from this map:
   *  it still gets output, it just doesn't constrain the size (see `resize`). `null` keys the
   *  relay host's detached sink, which has no ClientId but does report a size. */
  sizes: Map<ClientId | null, PtySize>
  /** The size each subscriber's xterm is believed to be rendering: the last authoritative size we
   *  sent it, or — if it has reported a fit since — its own fit (the renderer applies its own fit
   *  locally, exactly as it always has). We only send `pty:size` to a subscriber whose view differs
   *  from the effective size, which is what keeps a SOLO user's resize free of any extra IPC. */
  shown: Map<ClientId, PtySize>
  /** The size currently pushed into the pty (seeded from the spawn's cols/rows). Guards against
   *  re-resizing the tmux client to the size it already has — that is a full-pane redraw. */
  appliedSize?: PtySize
  /** The node id this session was created for, whether or not it is tmux-persisted — the key of
   *  the `byPersistKey` co-attach index (`persistKey` below is only set for PERSISTED sessions,
   *  because it also gates scrollback snapshots). Undefined for a relay-served (detached) pty,
   *  which is deliberately not indexed. */
  indexKey?: string
  /** Detached sinks: when set, output/exit ALSO go to these callbacks (relay host). */
  onData?: (data: string) => void
  onExit?: (exitCode: number) => void
  /** Pending output chunks, coalesced into one IPC message per flush. */
  buf: string[]
  bufBytes: number
  flushTimer: ReturnType<typeof setTimeout> | null
  /** Node id this session persists under (when tmux-backed) — used for scrollback snapshots. */
  persistKey?: string
  /** When set, the session runs on a remote host via ssh; kill/capture target the REMOTE tmux. */
  sshRemote?: NonNullable<PtyCreateOptions['sshRemote']>
  /** Output arrived since the last scrollback snapshot — idle sessions skip the capture. */
  outputSinceSnapshot: boolean
  /**
   * The clients that currently OWE us a resume: each has cast `pty:flow(sessionId,false)` because
   * ITS OWN xterm write-backlog crossed the high-water mark. The pty is paused while this set is
   * non-empty and resumes only when it becomes empty (`setFlow` / `releaseFlow`). `null` keys the
   * relay host's detached sink, which pauses on relay backpressure and has no ClientId.
   *
   * It has to be a SET, not a boolean, because both of these must hold at once:
   *  (a) a pause owed by a client that LEFT is always returned (its renderer is gone and will
   *      never send the matching resume — the co-attaching or remaining clients would stare at a
   *      frozen, blank terminal forever). `kill` / `dropClient` / `join` return it.
   *  (b) a pause owed by a client that is STILL HERE is never silently cancelled. That client's
   *      flow control is EDGE-latched (`if (!paused && pending > HIGH_WATER)` in TerminalNode) —
   *      once it has pumped the pause it will NOT re-pause, so resuming the pty behind its back is
   *      permanent and its write queue then grows without bound for the rest of the flood.
   * A single boolean can only ever satisfy one of the two (it cannot tell the cases apart).
   */
  pausedBy: Set<ClientId | null>
  /** True when this node had an `accountId` but its config dir was gone at spawn, so we fell back
   *  to the system account. `create()` surfaces it to the renderer (warning chip). */
  accountFallback?: boolean
}

/** Sinks for a detached session whose output is served somewhere other than the renderer
 * (the relay host). The PTY is otherwise identical to a normal session. */
export interface DetachedSinks {
  onData(data: string): void
  onExit(exitCode: number): void
}

/**
 * tmux attach flags. `-A` = attach-or-create. `-D` = detach OTHER clients on attach.
 *
 * `-D` STAYS for the app's own client, and co-attach does not change that: a second viewer
 * subscribes to the existing `Session` in this process — it does NOT start a second tmux client.
 * The app therefore always has exactly ONE tmux client per session, so tmux's own multi-client
 * size negotiation never engages and "smallest subscriber wins" is decided by us (pty-size.ts).
 * A relay-served (detached) pty is the one exception: the host's local client is already attached
 * to the same session and must be mirrored, not kicked off.
 */
export function tmuxAttachFlags(detached: boolean): string[] {
  return detached ? ['-A'] : ['-A', '-D']
}

// Output coalescing: a fast producer (e.g. `yes`, a verbose build, tmux full-screen
// redraws) emits many small chunks. Buffering them for one short window collapses N
// IPC messages + N xterm writes into one, which is the single hottest path in the app.
const FLUSH_MS = 8
const MAX_BUF_BYTES = 256 * 1024

/**
 * Manages all live PTY processes and bridges them to the renderer over IPC.
 *
 * On macOS/Linux with tmux available, each terminal node attaches to a persistent
 * tmux session named after its node id (`tmux new-session -A`). Closing a node's
 * window only detaches the client — the tmux session (and everything running in it)
 * survives, so reopening the node or restarting the app reattaches and continues
 * where it left off. Without tmux, it falls back to a plain shell (no persistence).
 */
export class PtyManager {
  private sessions = new Map<string, Session>()
  /** persistKey (node id) → live sessionId. The index that makes `pty:create` idempotent:
   *  a second client asking for the same node subscribes to the running session. */
  private byPersistKey = new Map<string, string>()
  /** persistKey (node id) → the create() currently spawning it. Makes `pty:create` idempotent
   *  ACROSS the awaits inside a spawn (see create()), not just after them. Entries are removed
   *  as soon as the spawn settles, success or failure. */
  private inflight = new Map<string, Promise<PtyCreateResult>>()
  private counter = 0
  private tmuxPath: string | null = null
  private confPath = ''
  private getSettings: () => Settings = () => DEFAULT_SETTINGS
  /** ONE shared snapshot interval for all persisted sessions — a per-session interval spawned
   *  one tmux/ssh capture subprocess per session per tick, forever, even for idle terminals. */
  private snapshotTimer: ReturnType<typeof setInterval> | null = null

  private ensureSnapshotTimer(): void {
    if (this.snapshotTimer) return
    this.snapshotTimer = setInterval(() => this.snapshotTick(), SCROLLBACK_SNAPSHOT_MS)
  }

  private snapshotTick(): void {
    let anyPersisted = false
    for (const session of this.sessions.values()) {
      if (!session.persistKey) continue
      anyPersisted = true
      if (!session.outputSinceSnapshot) continue // idle since the last capture — skip the spawn
      session.outputSinceSnapshot = false
      void this.snapshotScrollback(session.persistKey, session.sshRemote).then((ok) => {
        // Transient capture failure (ssh blip, tmux busy): put the dirty bit back so the next
        // tick retries — otherwise a quiet session would never be snapshotted again.
        if (!ok) session.outputSinceSnapshot = true
      })
    }
    if (!anyPersisted && this.snapshotTimer) {
      clearInterval(this.snapshotTimer)
      this.snapshotTimer = null
    }
  }

  /** Must run after app is ready (needs userData path). */
  init(getSettings: () => Settings): void {
    this.getSettings = getSettings
    // Prewarm the login-shell PATH probe now so the first terminal spawn doesn't wait on it.
    void resolveShellPath()
    this.tmuxPath = findTmux()
    if (!this.tmuxPath) return
    this.confPath = path.join(platform().userDataDir, 'tmux.conf')
    try {
      fs.writeFileSync(this.confPath, tmuxConf(getSettings().tmuxScrollback))
    } catch {
      // If we can't write the config, disable tmux and fall back to a plain shell.
      this.tmuxPath = null
      return
    }
    // The tmux server outlives the app, so it won't re-read `-f` on relaunch. Push the
    // (possibly updated) config into a running server now so new bindings apply immediately;
    // a no-op error when no server exists yet (the next session loads it fresh via `-f`).
    try {
      execFileSync(this.tmuxPath, ['-L', TMUX_SOCKET, 'source-file', this.confPath], {
        stdio: 'ignore'
      })
    } catch {
      // no server running yet — ignore
    }
  }

  /** Absolute tmux path (or null if tmux is unavailable). Used by the context-link backend. */
  getTmuxBin(): string | null {
    return this.tmuxPath
  }

  registerIpc(): void {
    platform().handleWithSender(
      IPC.ptyCreate,
      (senderId, options: PtyCreateOptions): Promise<PtyCreateResult> =>
        this.create(senderId, options)
    )
    platform().on(IPC.ptyWrite, (sessionId: string, data: string) =>
      this.write(sessionId, data)
    )
    // Sender-aware: a size is only meaningful with the client it belongs to — the pty runs at the
    // smallest one (`resize`). Registered ONLY here: `on` and `onWithSender` compose on the same
    // channel, so leaving the old plain listener in place would run the resize twice.
    platform().onWithSender(
      IPC.ptyResize,
      (senderId: number, sessionId: string, cols: number | null, rows: number | null) =>
        this.resize(senderId, sessionId, cols, rows)
    )
    // Sender-aware: a pause belongs to the client whose xterm backlog overflowed, and only that
    // client (or its departure) can return it — see `Session.pausedBy`. Registered ONLY here:
    // `on` and `onWithSender` compose on the same channel, so a leftover plain listener would
    // run the flow change twice (and, with an unattributed sessionId, wrongly).
    platform().onWithSender(
      IPC.ptyFlow,
      (senderId: number, sessionId: string, resume: boolean) =>
        this.setFlow(senderId, sessionId, resume)
    )
    // Sender-aware: with co-attach a kill detaches just THAT client, and the pty (and the tmux
    // session behind it) survives while any other subscriber is still watching.
    platform().onWithSender(IPC.ptyKill, (senderId: number, sessionId: string) =>
      this.kill(senderId, sessionId)
    )
    platform().on(IPC.ptyDestroy, (persistKey: string) => this.destroySession(persistKey))
    platform().handle(IPC.ptyReadScrollback, (persistKey: string) =>
      readScrollback(persistKey)
    )
    platform().handle(IPC.ptySendText, (persistKey: string, text: string) =>
      this.sendText(persistKey, text)
    )
  }

  private async create(clientId: ClientId, options: PtyCreateOptions): Promise<PtyCreateResult> {
    const key = options.persistKey
    if (!key) return this.spawnNew(clientId, options)
    // Co-attach: a live session for this node id already exists in THIS process (another client,
    // or this client's own second view). Subscribe to it instead of spawning a second tmux client
    // — `-D` would otherwise kick the first viewer off.
    const joined = this.join(clientId, options, key)
    if (joined) return joined
    // Same-tick race: spawnNew() awaits a `tmux has-session` SUBPROCESS (tens of ms, not a
    // microtask) before spawnSession registers the session in `byPersistKey`, so two clients
    // opening the same node in that window would BOTH miss the index and both spawn — and the
    // second `tmux -A -D` detaches the first client, killing that user's terminal. So the spawn
    // is published as an in-flight promise from the TOP of create(): a racing create awaits it
    // and then takes the subscribe branch. (No locking primitive: the promise IS the barrier —
    // the single-user path never sees an in-flight entry and behaves exactly as before.)
    const inflight = this.inflight.get(key)
    if (inflight) {
      await inflight.catch(() => undefined) // the other spawn failed → fall through and try ourselves
      const late = this.join(clientId, options, key)
      if (late) return late
      // The spawn we awaited REJECTED, so there is no session to join. With two clients queued
      // behind that one failure, the first of them re-spawns — and the second must see THAT spawn
      // (published below, synchronously) rather than fall through and spawn a second tmux client,
      // whose `-D` would detach the first. Recurse: the in-flight guard is the barrier, so waiting
      // on a *new* in-flight entry is exactly the same wait as the one we just did.
      if (this.inflight.get(key)) return this.create(clientId, options)
    }
    const spawn = this.spawnNew(clientId, options)
    this.inflight.set(key, spawn)
    // Clear on settle — INCLUDING on failure, or a single failed spawn would leave a rejected
    // promise in the map and make the node permanently unopenable.
    const clear = (): void => {
      if (this.inflight.get(key) === spawn) this.inflight.delete(key)
    }
    spawn.then(clear, clear)
    return spawn
  }

  /**
   * Subscribe `clientId` to the live session for this node id, if there is one. Returns the
   * create() result (`fresh:false` — the renderer joined a live session: no cold-restore
   * scrollback replay, no agent resume; tmux redraws instead), or undefined if none exists.
   */
  private join(
    clientId: ClientId,
    options: PtyCreateOptions,
    persistKey: string
  ): PtyCreateResult | undefined {
    const existingId = this.byPersistKey.get(persistKey)
    const existing = existingId ? this.sessions.get(existingId) : undefined
    if (!existingId || !existing) return undefined
    existing.subscribers.add(clientId)
    // The joiner's xterm has fitted itself to its own window; that is what it renders until we
    // tell it otherwise. applySize() then either shrinks the pty to it (it is the new smallest) or
    // sends it the authoritative size to render + letterbox.
    const size = normalizeSize(options.cols, options.rows)
    existing.sizes.set(clientId, size)
    existing.shown.set(clientId, size)
    this.applySize(existingId, existing)
    // A (re)joining client's backlog is empty by definition, so its fresh page will never issue a
    // resume its PREVIOUS page owed us — a renderer reload keeps the same ClientId, so without this
    // the reloaded terminal would stay frozen forever with no data arriving to unstick it. Return
    // only THIS client's owed pause: a pause owed by a DIFFERENT client that is still here and
    // still drowning stays in place (invariant (b) on `pausedBy`).
    this.releaseFlow(existing, clientId)
    // KNOWN GAP — plain-shell (tmux disabled / unavailable) co-attach: `fresh:false` makes the
    // renderer skip the cold-restore scrollback replay, and with no tmux there is no client to
    // redraw the screen either, so this joiner sees a blank-but-live terminal until the next
    // output arrives (typing Enter paints it). Not fixed here on purpose: the renderer only
    // subscribes to `pty:data:<id>` AFTER create() resolves, so a join-time repaint cannot be
    // pushed on the wire — it needs a new field on PtyCreateResult plus renderer replay, i.e. a
    // cross-surface contract change that belongs with the per-client backlog work (Task 5), not
    // in a bugfix. A plain-shell session has no cross-client continuity to inherit anyway (it is
    // exactly what "no tmux = no persistence" already means everywhere else in this file).
    return existing.accountFallback
      ? { sessionId: existingId, fresh: false, accountFallback: true }
      : { sessionId: existingId, fresh: false }
  }

  /** Spawn a brand-new session for this client (the non-co-attach path). */
  private async spawnNew(clientId: ClientId, options: PtyCreateOptions): Promise<PtyCreateResult> {
    // A tmux-backed session is "fresh" (cold start) when no live session exists to reattach to
    // — i.e. first open, or after a machine reboot killed the tmux server. Plain (non-tmux)
    // sessions are always fresh: they have no cross-restart continuity. The renderer uses this
    // to decide whether to replay the persisted scrollback and re-launch a resumable agent.
    const tmuxBacked =
      !!this.tmuxPath && this.getSettings().tmuxEnabled && !!options.persistKey
    // For an SSH-project node, "fresh" is decided by the REMOTE tmux server (over the project's
    // ControlMaster), not the local one. The remote `has-session` is a full network round-trip,
    // so it MUST be async (`runAsync`) — a synchronous probe here would freeze every window/IPC
    // for its duration. Falls through to the local tmux/plain logic otherwise (also async: a
    // bulk project load fires one create() per node, and even cheap probes add up serialized).
    const fresh = options.sshRemote
      ? !(await this.remoteSessionExists(
          options.sshRemote,
          sessionName(options.persistKey as string)
        ))
      : tmuxBacked
        ? !(await this.tmuxSessionExists(options.persistKey as string))
        : true
    // Ensure the login-shell PATH is resolved (prewarmed in init(); usually already settled)
    // so the session env below picks it up — awaiting keeps the event loop free either way.
    await resolveShellPath()
    const sessionId = this.spawnSession(options, clientId, undefined)
    // Surface a missing-account-dir fallback so the renderer can flag the node's account chip.
    const accountFallback = this.sessions.get(sessionId)?.accountFallback
    return accountFallback ? { sessionId, fresh, accountFallback } : { sessionId, fresh }
  }

  /** Does the node's remote tmux session exist (over the project's ControlMaster)? Async so the
   *  network round-trip never blocks the main event loop. */
  private async remoteSessionExists(
    sshRemote: NonNullable<PtyCreateOptions['sshRemote']>,
    sessionId: string
  ): Promise<boolean> {
    const ssh = findSsh()
    if (!ssh) return false
    try {
      await runAsync(ssh, remoteTmuxHasSessionArgs(sshRemote.conn, sshRemote.controlPath, sessionId))
      return true
    } catch {
      return false
    }
  }

  /** Find the live session registered under a node id (persistKey), if any. */
  private sessionByPersistKey(persistKey: string): Session | undefined {
    for (const session of this.sessions.values()) {
      if (session.persistKey === persistKey) return session
    }
    return undefined
  }

  /**
   * The live SSH-remote handle for a node id, if its session is running on a remote host.
   * Used by the remote context/subagent tails to read the node's transcript over the same
   * ControlMaster. Returns undefined for local sessions or unknown nodes.
   */
  sshRemoteForNode(
    nodeId: string
  ): { controlPath: string; conn: import('../shared/ssh').SshConnection } | undefined {
    const s = this.sessionByPersistKey(nodeId)
    if (!s?.sshRemote) return undefined
    return { controlPath: s.sshRemote.controlPath, conn: s.sshRemote.conn }
  }

  /** Whether a tmux session for this node id currently exists (server alive + session present).
   *  Async like the remote probe: a bulk project load fires one `create()` per terminal node,
   *  and a synchronous subprocess per probe would serialize on the main event loop. */
  private async tmuxSessionExists(persistKey: string): Promise<boolean> {
    if (!this.tmuxPath) return false
    try {
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'has-session', '-t', sessionName(persistKey)])
      return true
    } catch {
      return false
    }
  }

  /**
   * Spawn a PTY whose output/exit are delivered to `sinks` instead of the renderer. Used by
   * the relay host (Task 6) to serve PTYs over the E2EE transport: the host pipes `onData`
   * into `OP.Output` frames and maps client RPC/frames back to `write`/`resize`/`kill`. The
   * spawn (tmux session, hook env, shell selection) is identical to a normal renderer session.
   */
  createDetached(options: PtyCreateOptions, sinks: DetachedSinks): string {
    return this.spawnSession(options, null, sinks)
  }

  /**
   * Attach a detached (relay-served) PTY to the EXISTING tmux session for a node id, rather
   * than always creating a fresh one. Because `spawnSession` uses `tmux new-session -A`, passing
   * the node id as the `persistKey` reattaches the existing `nt-<nodeId>` session if it exists,
   * or creates it otherwise (graceful fallback). Used by the relay host so a mirrored terminal
   * resumes the host's live session instead of opening a blank shell. Pair with `captureSnapshot`
   * to paint the current screen before live output starts streaming. Because `sinks` is set here,
   * `spawnSession` attaches WITHOUT `-D` (co-attach), so the host's own local tmux client stays
   * attached and both the host and the mirroring client view the same session simultaneously.
   */
  attachDetached(
    persistKey: string,
    sinks: DetachedSinks,
    options: Omit<PtyCreateOptions, 'persistKey'> = { cols: 80, rows: 24 }
  ): string {
    return this.spawnSession({ ...options, persistKey }, null, sinks)
  }

  /**
   * Capture the CURRENT visible pane of a node's tmux session (with colors, via `-e`). Returns
   * the screen text so the relay host can send it as a snapshot the mirrored client paints before
   * live output. Empty string if tmux is unavailable or the session doesn't exist yet.
   */
  async captureSnapshot(persistKey: string): Promise<string> {
    if (!this.tmuxPath) return ''
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-e', '-t', sessionName(persistKey)],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      return stdout
    } catch {
      return ''
    }
  }

  private spawnSession(
    options: PtyCreateOptions,
    /** The client this session is spawned for, or null for a relay-served (detached) pty. */
    clientId: ClientId | null,
    sinks: DetachedSinks | undefined
  ): string {
    const sessionId = `pty-${++this.counter}`
    // For a remote (ssh-project) node the local PTY just holds the ssh client, so its local cwd
    // must be a real LOCAL directory (options.cwd is a REMOTE path that wouldn't exist locally and
    // would make pty.spawn throw). The remote working dir is passed to tmux via sshRemote.remoteCwd.
    let cwd = options.sshRemote ? os.homedir() : options.cwd || os.homedir()
    // `|| os.homedir()` only catches an EMPTY cwd. A cwd that is set but STALE — a project folder
    // the user deleted/unmounted — still reaches pty.spawn and makes posix_spawn fail. Verify the
    // directory actually exists and fall back to home if not, so a dead folder never kills the node.
    if (!options.sshRemote) {
      try {
        if (!fs.statSync(cwd).isDirectory()) cwd = os.homedir()
      } catch {
        cwd = os.homedir()
      }
    }

    // Strip TMUX so tmux doesn't refuse to nest if the app itself was launched
    // from inside a tmux session.
    const env = { ...process.env, TERM: 'xterm-256color' } as Record<string, string>
    delete env.TMUX
    delete env.TMUX_PANE

    // A GUI app launched from Finder/Dock inherits only a minimal PATH, so spawned terminals
    // couldn't find tools in /usr/local/bin, Homebrew, ~/.local/bin, nvm, bun, etc. (the classic
    // `command not found: claude`). Replace PATH with the user's real login-shell PATH so every
    // terminal — and any agent CLI it launches — resolves exactly what a normal terminal would.
    // Reads the cache filled by the async probe: create() awaits it, and the detached/host
    // paths spawn late enough that the init()-time prewarm has long since settled.
    const shellPath = cachedShellPath ?? null
    if (shellPath) env.PATH = shellPath

    // Same GUI-launch gap for the locale: with no LANG/LC_* the shell's `locale` is "C" (non-UTF-8),
    // so Claude Code and other TUIs fall back to ASCII box-drawing (rounded borders render as `_`/`|`).
    // Force a UTF-8 locale when the inherited env doesn't already declare one.
    const localeLang = resolveLocaleLang()
    if (localeLang) env.LANG = localeLang

    // Agent hooks: each session carries the hook-server coordinates + its node/agent id.
    // Our managed hook (installed globally in each agent's config, but a no-op without these
    // vars) then posts state back to us for any agent run in this session.
    // A REMOTE (ssh-project) session must NOT get the LOCAL hook env: it points at
    // 127.0.0.1:<localPort>, which is useless (and misleading) on the remote host. The remote
    // session's hook env is injected via the remote tmux `-e` below (from the reverse-tunnel
    // endpoint file), so leave the local hook env out entirely here.
    const hookEnv =
      options.persistKey && !options.sshRemote
        ? hookServer.buildPtyEnv(options.persistKey, options.agentId ?? 'claude')
        : {}
    for (const [k, v] of Object.entries(hookEnv)) env[k] = v

    // Managed Claude account: the whole session runs under the account's private config
    // dir. The claude CLI then reads/writes credentials + transcripts there. Also strip
    // env auth vars that would silently shadow the account's OAuth login (an inherited
    // ANTHROPIC_API_KEY wins over CLAUDE_CONFIG_DIR credentials). System-default nodes
    // (no accountId) are untouched. Remote (ssh) sessions get their account env via the
    // remote tmux `-e` list instead (the local ssh client process doesn't need it).
    let accountDir =
      options.accountId && !options.sshRemote ? claudeConfigDirFor(options.accountId) : null
    // Missing/deleted account dir (spec: error handling) → fall back to system default
    // instead of pointing claude at a dead dir; the node then behaves like an unbound one.
    // `accountFallback` is surfaced to the renderer (warning chip) via the create() result.
    let accountFallback = false
    if (accountDir && !fs.existsSync(accountDir)) {
      console.warn(`[accounts] config dir missing for ${options.accountId}, using system default`)
      accountDir = null
      accountFallback = true
    }
    if (accountDir) {
      env.CLAUDE_CONFIG_DIR = accountDir
      for (const k of AUTH_ENV_STRIP) delete env[k]
    }

    const settings = this.getSettings()
    let file: string
    let args: string[]

    // Resolve the session program. A bare 'ssh' is resolved to an absolute path because GUI
    // apps don't inherit the shell PATH; its args come from options.shellArgs.
    const reqShell = options.shell
    const program = reqShell === 'ssh' ? findSsh() ?? 'ssh' : reqShell
    const programArgs = options.shellArgs ?? []

    // SSH project node: run `ssh -t '<remote tmux attach-or-create>'` as the PTY program. The
    // REMOTE tmux provides persistence (over the project's ControlMaster); the local PTY just
    // holds the ssh client. Only when BOTH sshRemote and persistKey are set and ssh resolves —
    // otherwise this falls through to the unchanged local-tmux / plain-shell branches below.
    const remoteSsh = options.sshRemote && options.persistKey ? findSsh() : null
    if (options.sshRemote && options.persistKey && remoteSsh) {
      file = remoteSsh
      // When the project's reverse tunnel + remote endpoint file are set up (Task 2), inject the
      // remote hook env into the remote tmux session so the installed hook script POSTs state back
      // over the unix-socket tunnel. Fail-open: no hookEndpointPath → no hook env (Phase-1 status).
      //
      // NODETERM_NODE_ID MUST be the RAW persistKey (the React Flow node id), NOT the tmux
      // session name (`nt-<id>`). The local path's hookServer.buildPtyEnv(persistKey, …) sets
      // NODETERM_NODE_ID = persistKey, and Canvas.tsx onAgentStatus keys agentStatus.byId /
      // selection off that raw id with no `nt-` stripping. Passing the session name here would
      // emit events under `nt-<id>` that match no node → no badge/notification/session/loop.
      const hookExtraEnv = options.sshRemote.hookEndpointPath
        ? remoteHookEnvArgs(
            options.sshRemote.hookEndpointPath,
            options.persistKey,
            hookServer.getVersion()
          )
        : []
      // Managed REMOTE Claude account (Task 12): inject CLAUDE_CONFIG_DIR into the remote tmux
      // session via `-e`, pointing at the account's config dir on the remote host. The path must be
      // ABSOLUTE — tmux copies `-e` values verbatim (no `$HOME`/`~` expansion) — so we build it from
      // the connection's resolved remote $HOME. Fail-open: an unknown remoteHome (home resolution
      // failed on connect) skips the account env and the session runs under the remote `~/.claude`.
      const remoteAccountEnv =
        options.accountId && options.sshRemote.remoteHome
          ? accountTmuxEnvArgs(remoteAccountConfigDirAbs(options.sshRemote.remoteHome, options.accountId))
          : []
      args = remoteTmuxPtyArgs(
        options.sshRemote.conn,
        options.sshRemote.controlPath,
        sessionName(options.persistKey),
        options.sshRemote.remoteCwd,
        // An agent preset may pass a remote program to run inside the remote tmux; usually undefined.
        options.shell,
        options.shellArgs,
        [...hookExtraEnv, ...remoteAccountEnv],
        // Source nodeterm's remote tmux.conf via `-f` (written on connect, Task 2) so a cold-start
        // session gets mouse/clipboard/scrollback. Fail-open: undefined → remote tmux host defaults.
        options.sshRemote.tmuxConfPath
      )
    } else if (this.tmuxPath && settings.tmuxEnabled && options.persistKey) {
      // attach-or-create the persistent session for this node.
      // `-A` = attach-or-create. `-D` = detach OTHER clients on attach. We use `-D` ONLY for the
      // local renderer client (a remount should take sole ownership of its session). A host-served
      // PTY (sinks set) MUST NOT detach others: the host's own local client is attached to the same
      // `nt-<id>` session, and a connecting client should MIRROR it (tmux co-attach), not kick it
      // off — `-D` there is exactly what showed "[detached]" in every host window on connect.
      // (tmux sizes a co-attached session to the smallest client — the accepted mirroring tradeoff.)
      // `-e` sets the session environment explicitly (the tmux server is shared, so relying
      // on the client's inherited env would leak the first session's values into later ones).
      file = this.tmuxPath
      // The hook-server env (port/token/node id/agent id) is passed explicitly via `-e`
      // (one `-e KEY=VALUE` per key) since the shared tmux server can't rely on inherited env.
      const hookEnvArgs = Object.entries(hookEnv).flatMap(([k, v]) => ['-e', `${k}=${v}`])
      // Set the session PATH explicitly too: the tmux server is shared and long-lived (it outlives
      // the app), so a session created after an app update must NOT inherit a stale minimal PATH
      // baked into the server env at first launch — `-e` overrides it per new session at creation.
      const pathEnvArgs = env.PATH ? ['-e', `PATH=${env.PATH}`] : []
      // Same reasoning for LANG: force the UTF-8 locale per new session so a session created on a
      // shared/stale tmux server (started before this fix) still gets UTF-8 box-drawing.
      const langEnvArgs = env.LANG ? ['-e', `LANG=${env.LANG}`] : []
      // The account config dir must ride `-e` like the hook env: the tmux server is shared
      // and long-lived, so session env comes from creation args, not client inheritance.
      const accountEnvArgs = accountDir ? accountTmuxEnvArgs(accountDir) : []
      const attachFlags = tmuxAttachFlags(!!sinks)
      args = [
        '-L',
        TMUX_SOCKET,
        '-f',
        this.confPath,
        'new-session',
        ...attachFlags,
        ...hookEnvArgs,
        ...pathEnvArgs,
        ...langEnvArgs,
        ...accountEnvArgs,
        '-c',
        cwd,
        '-s',
        sessionName(options.persistKey)
      ]
      // Honor a custom session program at creation (ignored on reattach).
      const shell = program || settings.defaultShell
      if (shell) {
        args.push(shell)
        args.push(...programArgs)
      }
    } else {
      file =
        program ||
        settings.defaultShell ||
        process.env.SHELL ||
        (os.platform() === 'win32' ? 'powershell.exe' : 'bash')
      args = program ? programArgs : []
    }

    let proc: pty.IPty
    try {
      proc = pty.spawn(file, args, {
        name: 'xterm-256color',
        cols: options.cols,
        rows: options.rows,
        cwd,
        env
      })
    } catch (err) {
      // node-pty surfaces the underlying failure as a bare "posix_spawnp failed." with no errno.
      // The recurring field cause is a cross-arch `electron-builder --x64` run clobbering
      // node-pty's spawn-helper in node_modules (arm64 app can't exec an x86_64 helper), so
      // check the helper's Mach-O arch first and name the exact remedy when it mismatches.
      const openPtys = this.sessions.size
      const reason = err instanceof Error ? err.message : String(err)
      const archNote = spawnHelperArchMismatch()
      throw new Error(
        `Failed to spawn terminal (${reason}). Program: ${file}, cwd: ${cwd}, live PTYs: ${openPtys}. ` +
          (archNote ??
            `If this persists, restart the app (tmux sessions survive a restart) or run ` +
              `\`npm run rebuild\` in the repo — a release build may have rebuilt node-pty ` +
              `for the wrong architecture.`)
      )
    }

    // tmux-backed sessions snapshot their scrollback to disk periodically so a machine reboot
    // (which kills the tmux server) can still replay recent output on cold restart. A remote
    // (ssh-project) node is persisted too — the snapshot is captured from the REMOTE tmux.
    // Mark the session remote ONLY when the remote branch above actually ran (`remoteSsh` resolved).
    // If ssh is missing, the node fell through to a LOCAL tmux/plain spawn, so it must NOT be
    // marked remote — otherwise destroy/capture would target a remote tmux that was never spawned
    // and silently leak the local session.
    const remote = options.sshRemote && options.persistKey && remoteSsh ? options.sshRemote : undefined
    const tmuxBacked = !!(this.tmuxPath && settings.tmuxEnabled && options.persistKey)
    const persisted = !!options.persistKey && (remote ? true : tmuxBacked)
    const spawnSize = normalizeSize(options.cols, options.rows)
    const session: Session = {
      proc,
      subscribers: clientId === null ? new Set<ClientId>() : new Set<ClientId>([clientId]),
      sizes:
        clientId === null
          ? new Map<ClientId | null, PtySize>()
          : new Map<ClientId | null, PtySize>([[clientId, spawnSize]]),
      shown:
        clientId === null
          ? new Map<ClientId, PtySize>()
          : new Map<ClientId, PtySize>([[clientId, spawnSize]]),
      // node-pty was just spawned with these cols/rows, so the pty ALREADY has this size — record
      // it so a co-attach (or a fit that reports the same numbers) doesn't ioctl it needlessly.
      // A detached (relay-served) pty is left unseeded: its first `resize` must reach the pty,
      // exactly as before, because its sink never reports a size at create time.
      appliedSize: clientId === null ? undefined : spawnSize,
      indexKey: options.persistKey && !sinks ? options.persistKey : undefined,
      onData: sinks?.onData,
      onExit: sinks?.onExit,
      buf: [],
      bufBytes: 0,
      flushTimer: null,
      persistKey: persisted ? options.persistKey : undefined,
      sshRemote: remote,
      outputSinceSnapshot: true, // capture the initial screen on the first tick
      pausedBy: new Set<ClientId | null>(),
      accountFallback
    }
    if (persisted) this.ensureSnapshotTimer()
    this.sessions.set(sessionId, session)
    // Index by node id even when the session is NOT tmux-persisted (`persisted` only governs
    // scrollback snapshots): co-attach must work for a plain-shell session too. Detached
    // (relay-served) ptys are deliberately NOT indexed — the relay path keeps its own session,
    // exactly as before, so this change cannot regress it.
    if (session.indexKey) this.byPersistKey.set(session.indexKey, sessionId)

    proc.onData((data) => this.queueData(sessionId, session, data))

    proc.onExit(({ exitCode }) => {
      this.flush(sessionId, session) // deliver any buffered output before the exit signal
      session.onExit?.(exitCode) // relay host sink (unchanged)
      for (const sub of session.subscribers) this.send(sub, IPC.ptyExit(sessionId), exitCode)
      this.forget(sessionId, session)
    })

    return sessionId
  }

  /** Drop a dead/released session from both indexes. Keyed off `indexKey` (not `persistKey`,
   *  which is only set for tmux-PERSISTED sessions) so a plain-shell node is un-indexed too. */
  private forget(sessionId: string, session: Session): void {
    this.sessions.delete(sessionId)
    if (session.indexKey && this.byPersistKey.get(session.indexKey) === sessionId)
      this.byPersistKey.delete(session.indexKey)
  }

  /**
   * Push the effective (smallest-subscriber) size into the pty, then tell every subscriber whose
   * xterm is NOT already rendering that grid what it actually is, so each one renders exactly the
   * pty's grid (and letterboxes the leftover space) instead of its own `fit()` guess.
   *
   * Two separate idempotence guards, both load-bearing:
   *  - the pty is only resized when the effective size CHANGED (a same-size ioctl makes the tmux
   *    client redraw the whole pane for nothing);
   *  - a subscriber is only messaged when the size differs from what it is showing. With exactly
   *    one (viewing) subscriber the min of a one-element set is that subscriber's own fit, so a
   *    solo user is never sent a `pty:size` at all — the single-user path is unchanged.
   */
  private applySize(sessionId: string, session: Session): void {
    const size = effectiveSize(session.sizes.values())
    // Nobody is looking (every subscriber is parked, or none has reported a fit yet): leave the
    // pty at whatever size it has. Resizing it to a default here would garble the parked xterms'
    // buffers and the tmux pane behind them for no viewer's benefit.
    if (!size) return
    if (session.appliedSize?.cols !== size.cols || session.appliedSize?.rows !== size.rows) {
      session.appliedSize = size
      try {
        session.proc.resize(size.cols, size.rows)
      } catch {
        // resize can throw if the proc already exited; ignore.
      }
    }
    const channel = IPC.ptySize(sessionId)
    for (const sub of session.subscribers) {
      const shown = session.shown.get(sub)
      if (shown && shown.cols === size.cols && shown.rows === size.rows) continue
      session.shown.set(sub, size)
      this.send(sub, channel, size)
    }
  }

  /** Buffer a chunk; flush immediately past the byte cap, otherwise on a short timer. */
  private queueData(sessionId: string, session: Session, data: string): void {
    session.outputSinceSnapshot = true
    session.buf.push(data)
    session.bufBytes += data.length
    if (session.bufBytes >= MAX_BUF_BYTES) {
      this.flush(sessionId, session)
    } else if (!session.flushTimer) {
      session.flushTimer = setTimeout(() => this.flush(sessionId, session), FLUSH_MS)
    }
  }

  /** Send all buffered output for a session to every subscriber as a single IPC message. */
  private flush(sessionId: string, session: Session): void {
    if (session.flushTimer) {
      clearTimeout(session.flushTimer)
      session.flushTimer = null
    }
    if (session.buf.length === 0) return
    const data = session.buf.join('')
    session.buf = []
    session.bufBytes = 0
    session.onData?.(data) // relay host sink (unchanged)
    const channel = IPC.ptyData(sessionId)
    for (const sub of session.subscribers) this.send(sub, channel, data)
  }

  /**
   * Flow control: a client pauses us when ITS xterm write backlog grows past a high watermark and
   * resumes once it drains, so a flood can't grow that renderer's buffer without bound. node-pty
   * pause()/resume() stops/starts reading the pty fd; the OS pipe applies backpressure to the
   * producing process.
   *
   * Co-attach makes this per-client: there is ONE pty behind N subscribers, so it must be paused
   * while ANY subscriber is behind (the slowest viewer sets the pace — the alternative, dropping
   * output for the laggard, needs a per-client backlog and a redraw, which is Task 5) and resumed
   * only when the LAST owed resume lands. `pausedBy` is that ledger.
   *
   * `clientId` is null for the relay host's detached pty, whose sink pauses on relay backpressure
   * and returns the resume on drain — one more owner in the same ledger, no special casing.
   *
   * Single user: the set holds exactly his ClientId while paused and is empty when he resumes, so
   * the actuator sees exactly the pause/resume pair it always saw.
   */
  setFlow(clientId: ClientId | null, sessionId: string, resume: boolean): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    if (resume) {
      this.releaseFlow(session, clientId)
      return
    }
    const wasPaused = session.pausedBy.size > 0
    session.pausedBy.add(clientId)
    if (wasPaused) return // already paused by someone — pause() again would be a no-op
    try {
      session.proc.pause()
    } catch {
      // pause can throw if the proc already exited; ignore.
    }
  }

  /**
   * Return the pause `clientId` owed us — because it resumed, or because it LEFT (kill /
   * dropClient) or reloaded (join). The pty resumes only when the ledger empties: a pause still
   * owed by a client that is here and behind must survive every other client's comings and goings,
   * or that client's renderer queue grows without bound (its flow control is edge-latched and will
   * never re-pause). No-op when this client owed nothing — the single-user resume path is then
   * exactly the old `paused=false; proc.resume()`.
   */
  private releaseFlow(session: Session, clientId: ClientId | null): void {
    if (!session.pausedBy.delete(clientId)) return
    if (session.pausedBy.size > 0) return
    try {
      session.proc.resume()
    } catch {
      // resume can throw if the proc already exited; ignore.
    }
  }

  write(sessionId: string, data: string): void {
    this.sessions.get(sessionId)?.proc.write(data)
  }

  /**
   * A subscriber reports the size IT can render. The pty runs at the smallest of them, so nobody
   * is ever sent more columns than their xterm can draw (a subscriber with room to spare
   * letterboxes the remainder). With exactly one subscriber, min(one) is that subscriber's own
   * size — the single-user path resizes the pty to exactly what it asked for, as it always did.
   *
   * A `null` cols/rows means **"subscribed, but not looking"**: the client stays in the fan-out
   * (it keeps consuming output) but drops out of the min. This is what a PARKED terminal reports —
   * the renderer keeps an unmounted node's xterm+PTY alive for 5 minutes so a remount re-adopts
   * them exactly, and without this a window somebody parked small would keep every other viewer's
   * terminal shrunk for those 5 minutes even though nobody is looking at it. `null` (not 0) carries
   * that meaning because 0 already has one: `effectiveSize` clamps a not-yet-measured VIEWING
   * client's 0 up to 1 rather than letting it zero the pty.
   *
   * `clientId` is null for the relay host's detached pty (its sink reports the mirrored client's
   * size); it constrains the size like any other viewer but is not in `subscribers`, so it gets no
   * `pty:size` message — the relay has its own size channel.
   */
  resize(
    clientId: ClientId | null,
    sessionId: string,
    cols: number | null,
    rows: number | null
  ): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    if (cols === null || rows === null) {
      session.sizes.delete(clientId)
    } else {
      const size = normalizeSize(cols, rows)
      session.sizes.set(clientId, size)
      // The client's own xterm fits itself locally (as it always has), so its fit — not the last
      // authoritative size we sent it — is what it is rendering right now. If that fit isn't the
      // effective size, applySize() below corrects it straight back.
      if (clientId !== null) session.shown.set(clientId, size)
    }
    this.applySize(sessionId, session)
  }

  /**
   * One client detaches (node unmount / tab close). With co-attach this is per-CLIENT: the pty
   * (and the tmux session behind it) survives while anyone else is still watching. Only when the
   * last subscriber leaves — and no relay sink is attached — do we release the pty client. With
   * tmux the tmux session itself keeps running either way, as always.
   *
   * `clientId` is null for the relay host releasing its own detached (sink-served) pty: it drops
   * the sinks, which are that session's only "subscriber".
   */
  kill(clientId: ClientId | null, sessionId: string): void {
    const session = this.sessions.get(sessionId)
    if (!session) return
    if (clientId === null) {
      session.onData = undefined
      session.onExit = undefined
      session.sizes.delete(null)
    } else {
      session.subscribers.delete(clientId)
      session.sizes.delete(clientId)
      session.shown.delete(clientId)
    }
    // The departing client (or sink) may have been one of the ones that paused us, and it will
    // never send the matching resume now — leaving that pause in place would freeze the terminal
    // for everyone who stayed. A pause owed by a client that is STILL here is untouched: the pty
    // stays paused until IT drains (its renderer cannot re-pause — see `Session.pausedBy`).
    this.releaseFlow(session, clientId)
    if (session.subscribers.size > 0 || session.onData) {
      // Somebody is still watching: the departing client's size no longer constrains the pty.
      this.applySize(sessionId, session)
      return
    }
    if (session.flushTimer) clearTimeout(session.flushTimer)
    // Final snapshot on detach (node unmount / app quit) so the very latest scrollback survives
    // a reboot. The tmux session itself keeps running, so this only races a same-instant capture.
    // Skipped when nothing arrived since the last periodic capture (pane content is unchanged).
    if (session.persistKey && session.outputSinceSnapshot)
      void this.snapshotScrollback(session.persistKey, session.sshRemote)
    // releasePty (not proc.kill()): a paused pty never reads EOF, so kill() alone leaks the
    // master fd on every detach until the process runs out of descriptors (see pty-release.ts).
    releasePty(session.proc as ReleasablePty)
    this.forget(sessionId, session)
  }

  /**
   * A client VANISHED (browser tab closed — the normal way to leave the Server Edition — or a
   * destroyed/crashed renderer): unsubscribe it from every session it was watching, exactly as a
   * `pty:kill` per session would. Sessions that fall to zero subscribers are released (final
   * scrollback snapshot + pty client released). tmux sessions are NOT killed — releasing the pty
   * client is the whole point: the terminal keeps running and the next open reattaches.
   *
   * Without this, a vanished client stays in `subscribers` forever: the pty is never released,
   * its detach-time snapshot never taken, and — worse — a pty that client had PAUSED could never
   * be resumed (the leave path is what returns the owed resume).
   */
  dropClient(clientId: ClientId): void {
    // Snapshot the entries: kill() mutates `sessions` when a session falls to zero subscribers.
    for (const [sessionId, session] of [...this.sessions]) {
      if (!session.subscribers.has(clientId)) continue
      this.kill(clientId, sessionId)
    }
  }

  /**
   * Capture a session's output. `full` grabs the entire scrollback (`-S -`, for the
   * markdown view); otherwise the recent ~200 lines (AI naming, palette search).
   */
  async captureSession(persistKey: string, full = false): Promise<string> {
    // Remote (ssh-project) node: there is no local tmux session — capture from the REMOTE tmux
    // over the project's ControlMaster (mirrors snapshotScrollback / destroySession).
    const sshRemote = this.sessionByPersistKey(persistKey)?.sshRemote
    if (sshRemote) {
      const ssh = findSsh()
      if (!ssh) return ''
      try {
        const { stdout } = await runAsync(
          ssh,
          remoteCapturePaneArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey), full),
          { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
        )
        return stdout
      } catch {
        return ''
      }
    }
    if (!this.tmuxPath) return ''
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-t', sessionName(persistKey), '-S', full ? '-' : '-200'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      return stdout
    } catch {
      return ''
    }
  }

  /**
   * The CURRENT screen of a live session, by sessionId — the redraw sent to a client that fell so
   * far behind that its socket backlog was discarded (see ServerPlatform's WS_DROP_WATER). Reuses
   * the existing `tmux capture-pane -e` paths (`captureSnapshot`, which the relay host already
   * paints a joining mirror with; `captureSession` for an ssh-project node, whose tmux lives on the
   * remote host) rather than adding a second capture. '' when the session or tmux is unavailable —
   * the client then just clears and resumes streaming.
   */
  async captureForResync(sessionId: string): Promise<string> {
    const session = this.sessions.get(sessionId)
    if (!session) return ''
    const key = session.persistKey ?? session.indexKey
    if (!key) return ''
    if (session.sshRemote) return this.captureSession(key)
    return this.captureSnapshot(key)
  }

  /**
   * Snapshot a node's recent scrollback (with colors, `-e`) to disk for cold-restart replay.
   * Best-effort: a missing session / unavailable tmux just leaves the prior snapshot in place.
   * Returns false when the capture failed, so the periodic tick can re-mark the session dirty
   * and retry (the dirty bit is cleared optimistically before the capture starts).
   */
  private async snapshotScrollback(
    persistKey: string,
    sshRemote?: NonNullable<PtyCreateOptions['sshRemote']>
  ): Promise<boolean> {
    if (sshRemote) {
      // Remote (ssh-project) node: capture from the REMOTE tmux over the project's ControlMaster.
      const ssh = findSsh()
      if (!ssh) return false
      try {
        const { stdout } = await runAsync(
          ssh,
          remoteCapturePaneArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey), false),
          { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
        )
        if (stdout) await writeScrollback(persistKey, stdout)
        return true
      } catch {
        // remote session gone / master down — keep the last good snapshot
        return false
      }
    }
    if (!this.tmuxPath) return false
    try {
      const { stdout } = await runAsync(
        this.tmuxPath,
        ['-L', TMUX_SOCKET, 'capture-pane', '-p', '-e', '-t', sessionName(persistKey), '-S', '-1500'],
        { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
      )
      if (stdout) await writeScrollback(persistKey, stdout)
      return true
    } catch {
      // session gone / tmux unavailable — keep the last good snapshot
      return false
    }
  }

  /**
   * Send literal text followed by Enter into a node's tmux session (e.g. a slash command).
   * Works whether or not a client is attached. Returns false if tmux is unavailable or the
   * session doesn't exist yet.
   */
  async sendText(persistKey: string, text: string): Promise<boolean> {
    if (!this.tmuxPath) return false
    const target = sessionName(persistKey)
    try {
      // The literal text and the Enter must be sent in order, so await sequentially.
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, '-l', text])
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'send-keys', '-t', target, 'Enter'])
      return true
    } catch {
      return false
    }
  }

  /**
   * List the names of all live nodeterm tmux sessions (on our dedicated socket). Used by the
   * relay host's `projects.list` RPC so a paired phone can enumerate the host's sessions the same
   * way the SSH browse path does (`tmux -L node-terminal list-sessions`). Returns the trimmed,
   * non-empty session names; `[]` on any error (tmux unavailable / no server / no sessions) so it
   * never throws.
   */
  async listNodetermSessions(): Promise<string[]> {
    if (!this.tmuxPath) return []
    try {
      const { stdout } = await runAsync(this.tmuxPath, [
        '-L',
        TMUX_SOCKET,
        'list-sessions',
        '-F',
        '#{session_name}'
      ])
      return stdout
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line.length > 0)
    } catch {
      return []
    }
  }

  /** Permanently end a node's persistent tmux session (called when the user closes it). */
  async destroySession(persistKey: string): Promise<void> {
    // destroy() is called (close button) while the session is still live, so its sshRemote is
    // known. Capture it synchronously before any await.
    const sshRemote = this.sessionByPersistKey(persistKey)?.sshRemote
    // Un-index NOW (synchronously): the node is gone for good, so a create() that races the
    // kill-session below — the worktree-move respawn does exactly that — must spawn a fresh
    // session instead of co-attaching to the one we are about to destroy. The Session object
    // itself is dropped by its own onExit / the client's kill().
    // Also drop any in-flight create for this node: a create racing the kill-session below must
    // spawn a fresh session, not await (and then join) the one we are destroying.
    this.inflight.delete(persistKey)
    const dyingId = this.byPersistKey.get(persistKey)
    if (dyingId) {
      this.byPersistKey.delete(persistKey)
      const dying = this.sessions.get(dyingId)
      if (dying) dying.indexKey = undefined
    }
    // The node is gone for good — drop its cold-restore snapshot too.
    await deleteScrollback(persistKey)
    if (sshRemote) {
      // Remote (ssh-project) node: there is no local tmux session — end the REMOTE one.
      const ssh = findSsh()
      if (!ssh) return
      try {
        await runAsync(ssh, remoteTmuxKillArgs(sshRemote.conn, sshRemote.controlPath, sessionName(persistKey)))
      } catch {
        // remote session may not exist / master down; ignore
      }
      return
    }
    if (!this.tmuxPath) return
    try {
      await runAsync(this.tmuxPath, ['-L', TMUX_SOCKET, 'kill-session', '-t', sessionName(persistKey)])
    } catch {
      // session may not exist; ignore
    }
  }

  /**
   * On quit, detach all clients (do NOT kill tmux sessions — that's the whole point
   * of persistence). The tmux server keeps the sessions alive for next launch.
   */
  /** Returns a promise of the final scrollback snapshots: the capture + write are async, so
   *  the quit path must hold `before-quit` briefly (see index.ts) or the process exits before
   *  they land and the last ≤15s of output is missing from a post-reboot cold restore. */
  killAll(): Promise<void> {
    if (this.snapshotTimer) {
      clearInterval(this.snapshotTimer)
      this.snapshotTimer = null
    }
    const finals: Promise<unknown>[] = []
    for (const session of this.sessions.values()) {
      if (session.flushTimer) clearTimeout(session.flushTimer)
      // Final scrollback snapshot on quit so a reboot can replay it. Skipped for sessions with
      // no output since the last periodic capture (unchanged pane content).
      if (session.persistKey && session.outputSinceSnapshot)
        finals.push(this.snapshotScrollback(session.persistKey, session.sshRemote))
      releasePty(session.proc as ReleasablePty)
    }
    this.sessions.clear()
    this.byPersistKey.clear()
    // Clear the in-flight index with the other two, or a create still spawning at quit would leave
    // a promise (and the session it resolves to) reachable from a manager that has released
    // everything else — a later create would then co-attach to a session we already let go.
    this.inflight.clear()
    return Promise.all(finals).then(() => undefined)
  }

  private send(clientId: ClientId, channel: string, payload: unknown): void {
    platform().sendTo(clientId, channel, payload)
  }
}
